/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\WebFontEnd\\Projects\\indulge-back-blog-devlopment\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-3e68fda2",
    path: "/BlogItem/Arrays%E7%9A%84%E9%9D%99%E6%80%81%E6%96%B9%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e68fda2").then(next)
    },
  },
  {
    path: "/BlogItem/Arrays的静态方法.html",
    redirect: "/BlogItem/Arrays%E7%9A%84%E9%9D%99%E6%80%81%E6%96%B9%E6%B3%95.html"
  },
  {
    path: "/BlogItem/Arrays的静态方法.html",
    redirect: "/BlogItem/Arrays%E7%9A%84%E9%9D%99%E6%80%81%E6%96%B9%E6%B3%95.html"
  },
  {
    name: "v-03ea0756",
    path: "/BlogItem/DOM%E5%92%8CBOM%E6%95%99%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03ea0756").then(next)
    },
  },
  {
    path: "/BlogItem/DOM和BOM教程.html",
    redirect: "/BlogItem/DOM%E5%92%8CBOM%E6%95%99%E7%A8%8B.html"
  },
  {
    path: "/BlogItem/DOM和BOM教程.html",
    redirect: "/BlogItem/DOM%E5%92%8CBOM%E6%95%99%E7%A8%8B.html"
  },
  {
    name: "v-af2edb96",
    path: "/BlogItem/Git%20%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-af2edb96").then(next)
    },
  },
  {
    path: "/BlogItem/Git 基础教程.html",
    redirect: "/BlogItem/Git%20%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B.html"
  },
  {
    path: "/BlogItem/Git 基础教程.html",
    redirect: "/BlogItem/Git%20%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B.html"
  },
  {
    name: "v-28acc7f4",
    path: "/BlogItem/JavaScript%E8%BF%9B%E9%98%B6%E6%95%99%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28acc7f4").then(next)
    },
  },
  {
    path: "/BlogItem/JavaScript进阶教程.html",
    redirect: "/BlogItem/JavaScript%E8%BF%9B%E9%98%B6%E6%95%99%E7%A8%8B.html"
  },
  {
    path: "/BlogItem/JavaScript进阶教程.html",
    redirect: "/BlogItem/JavaScript%E8%BF%9B%E9%98%B6%E6%95%99%E7%A8%8B.html"
  },
  {
    name: "v-1de00e7b",
    path: "/BlogItem/Lambda%20%E8%A1%A8%E8%BE%BE%E5%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1de00e7b").then(next)
    },
  },
  {
    path: "/BlogItem/Lambda 表达式.html",
    redirect: "/BlogItem/Lambda%20%E8%A1%A8%E8%BE%BE%E5%BC%8F.html"
  },
  {
    path: "/BlogItem/Lambda 表达式.html",
    redirect: "/BlogItem/Lambda%20%E8%A1%A8%E8%BE%BE%E5%BC%8F.html"
  },
  {
    name: "v-1c946e75",
    path: "/BlogItem/Mock.js%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1c946e75").then(next)
    },
  },
  {
    path: "/BlogItem/Mock.js快速入门.html",
    redirect: "/BlogItem/Mock.js%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html"
  },
  {
    path: "/BlogItem/Mock.js快速入门.html",
    redirect: "/BlogItem/Mock.js%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html"
  },
  {
    name: "v-76aa7db6",
    path: "/BlogItem/Pinia%E5%85%A5%E9%97%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-76aa7db6").then(next)
    },
  },
  {
    path: "/BlogItem/Pinia入门.html",
    redirect: "/BlogItem/Pinia%E5%85%A5%E9%97%A8.html"
  },
  {
    path: "/BlogItem/Pinia入门.html",
    redirect: "/BlogItem/Pinia%E5%85%A5%E9%97%A8.html"
  },
  {
    name: "v-c07dbf08",
    path: "/BlogItem/Node.js%E6%95%99%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c07dbf08").then(next)
    },
  },
  {
    path: "/BlogItem/Node.js教程.html",
    redirect: "/BlogItem/Node.js%E6%95%99%E7%A8%8B.html"
  },
  {
    path: "/BlogItem/Node.js教程.html",
    redirect: "/BlogItem/Node.js%E6%95%99%E7%A8%8B.html"
  },
  {
    name: "v-a2730a74",
    path: "/BlogItem/SpringBootWeb%20-%20AOP.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a2730a74").then(next)
    },
  },
  {
    path: "/BlogItem/SpringBootWeb - AOP.html",
    redirect: "/BlogItem/SpringBootWeb%20-%20AOP.html"
  },
  {
    path: "/BlogItem/SpringBootWeb - AOP.html",
    redirect: "/BlogItem/SpringBootWeb%20-%20AOP.html"
  },
  {
    name: "v-ba2d4322",
    path: "/BlogItem/TypeScript%E8%BF%9B%E9%98%B6%E8%AF%AD%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ba2d4322").then(next)
    },
  },
  {
    path: "/BlogItem/TypeScript进阶语法.html",
    redirect: "/BlogItem/TypeScript%E8%BF%9B%E9%98%B6%E8%AF%AD%E6%B3%95.html"
  },
  {
    path: "/BlogItem/TypeScript进阶语法.html",
    redirect: "/BlogItem/TypeScript%E8%BF%9B%E9%98%B6%E8%AF%AD%E6%B3%95.html"
  },
  {
    name: "v-2707771a",
    path: "/BlogItem/TypeScript%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2707771a").then(next)
    },
  },
  {
    path: "/BlogItem/TypeScript基础语法.html",
    redirect: "/BlogItem/TypeScript%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html"
  },
  {
    path: "/BlogItem/TypeScript基础语法.html",
    redirect: "/BlogItem/TypeScript%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html"
  },
  {
    name: "v-a6a3607c",
    path: "/BlogItem/vue3%20%E2%85%A0%20vue%20%E5%9F%BA%E7%A1%80%E5%85%A5%E9%97%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a6a3607c").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅰ vue 基础入门.html",
    redirect: "/BlogItem/vue3%20%E2%85%A0%20vue%20%E5%9F%BA%E7%A1%80%E5%85%A5%E9%97%A8.html"
  },
  {
    path: "/BlogItem/vue3 Ⅰ vue 基础入门.html",
    redirect: "/BlogItem/vue3%20%E2%85%A0%20vue%20%E5%9F%BA%E7%A1%80%E5%85%A5%E9%97%A8.html"
  },
  {
    name: "v-b9fb28f6",
    path: "/BlogItem/vue3%20%E2%85%A1%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8A%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b9fb28f6").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅱ vue 组件基础（上）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A1%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8A%EF%BC%89.html"
  },
  {
    path: "/BlogItem/vue3 Ⅱ vue 组件基础（上）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A1%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8A%EF%BC%89.html"
  },
  {
    name: "v-964a33f6",
    path: "/BlogItem/vue3%20%E2%85%A2%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8B%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-964a33f6").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅲ vue 组件基础（下）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A2%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8B%EF%BC%89.html"
  },
  {
    path: "/BlogItem/vue3 Ⅲ vue 组件基础（下）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A2%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8B%EF%BC%89.html"
  },
  {
    name: "v-656f9ebb",
    path: "/BlogItem/vue3%20%E2%85%A3%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8A%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-656f9ebb").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅳ vue 组件高级（上）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A3%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8A%EF%BC%89.html"
  },
  {
    path: "/BlogItem/vue3 Ⅳ vue 组件高级（上）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A3%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8A%EF%BC%89.html"
  },
  {
    name: "v-7748193b",
    path: "/BlogItem/vue3%20%E2%85%A4%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8B%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7748193b").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅴ vue 组件高级（下）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A4%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8B%EF%BC%89.html"
  },
  {
    path: "/BlogItem/vue3 Ⅴ vue 组件高级（下）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A4%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8B%EF%BC%89.html"
  },
  {
    name: "v-9d78ab64",
    path: "/BlogItem/vue3%20%E2%85%A5%20vue%20%E8%B7%AF%E7%94%B1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9d78ab64").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅵ vue 路由.html",
    redirect: "/BlogItem/vue3%20%E2%85%A5%20vue%20%E8%B7%AF%E7%94%B1.html"
  },
  {
    path: "/BlogItem/vue3 Ⅵ vue 路由.html",
    redirect: "/BlogItem/vue3%20%E2%85%A5%20vue%20%E8%B7%AF%E7%94%B1.html"
  },
  {
    name: "v-4f28a414",
    path: "/BlogItem/vue3%20%E2%85%A6%20vue%20%E8%A1%A5%E5%85%85%E5%86%85%E5%AE%B9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f28a414").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅶ vue 补充内容.html",
    redirect: "/BlogItem/vue3%20%E2%85%A6%20vue%20%E8%A1%A5%E5%85%85%E5%86%85%E5%AE%B9.html"
  },
  {
    path: "/BlogItem/vue3 Ⅶ vue 补充内容.html",
    redirect: "/BlogItem/vue3%20%E2%85%A6%20vue%20%E8%A1%A5%E5%85%85%E5%86%85%E5%AE%B9.html"
  },
  {
    name: "v-cc371236",
    path: "/BlogItem/vue3%20%E2%85%A7%20vue%20%E5%B8%B8%E8%A7%81%E4%BC%98%E5%8C%96%E6%89%8B%E6%AE%B5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cc371236").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅷ vue 常见优化手段.html",
    redirect: "/BlogItem/vue3%20%E2%85%A7%20vue%20%E5%B8%B8%E8%A7%81%E4%BC%98%E5%8C%96%E6%89%8B%E6%AE%B5.html"
  },
  {
    path: "/BlogItem/vue3 Ⅷ vue 常见优化手段.html",
    redirect: "/BlogItem/vue3%20%E2%85%A7%20vue%20%E5%B8%B8%E8%A7%81%E4%BC%98%E5%8C%96%E6%89%8B%E6%AE%B5.html"
  },
  {
    name: "v-25305652",
    path: "/BlogItem/vue3%E4%B8%8E%E7%BB%84%E5%90%88%E5%BC%8FAPI.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25305652").then(next)
    },
  },
  {
    path: "/BlogItem/vue3与组合式API.html",
    redirect: "/BlogItem/vue3%E4%B8%8E%E7%BB%84%E5%90%88%E5%BC%8FAPI.html"
  },
  {
    path: "/BlogItem/vue3与组合式API.html",
    redirect: "/BlogItem/vue3%E4%B8%8E%E7%BB%84%E5%90%88%E5%BC%8FAPI.html"
  },
  {
    name: "v-28fd3a72",
    path: "/BlogItem/%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28fd3a72").then(next)
    },
  },
  {
    path: "/BlogItem/微信支付.html",
    redirect: "/BlogItem/%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98.html"
  },
  {
    path: "/BlogItem/微信支付.html",
    redirect: "/BlogItem/%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98.html"
  },
  {
    name: "v-cbb13aa4",
    path: "/BlogItem/%E6%88%91%E4%BB%AC%E7%9A%84%E6%95%85%E4%BA%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cbb13aa4").then(next)
    },
  },
  {
    path: "/BlogItem/我们的故事.html",
    redirect: "/BlogItem/%E6%88%91%E4%BB%AC%E7%9A%84%E6%95%85%E4%BA%8B.html"
  },
  {
    path: "/BlogItem/我们的故事.html",
    redirect: "/BlogItem/%E6%88%91%E4%BB%AC%E7%9A%84%E6%95%85%E4%BA%8B.html"
  },
  {
    name: "v-7c16f5de",
    path: "/BlogItem/%E8%B7%AF%E5%BE%84%E5%88%AB%E5%90%8D%20ElementPlus%20Sass%E9%85%8D%E7%BD%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c16f5de").then(next)
    },
  },
  {
    path: "/BlogItem/路径别名 ElementPlus Sass配置.html",
    redirect: "/BlogItem/%E8%B7%AF%E5%BE%84%E5%88%AB%E5%90%8D%20ElementPlus%20Sass%E9%85%8D%E7%BD%AE.html"
  },
  {
    path: "/BlogItem/路径别名 ElementPlus Sass配置.html",
    redirect: "/BlogItem/%E8%B7%AF%E5%BE%84%E5%88%AB%E5%90%8D%20ElementPlus%20Sass%E9%85%8D%E7%BD%AE.html"
  },
  {
    name: "v-6ac3a860",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ac3a860").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-18082c7a",
    path: "/tag/Java/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-18082c7a").then(next)
    },
    meta: {"pid":"tags","id":"Java"}
  },
  {
    path: "/tag/Java/index.html",
    redirect: "/tag/Java/"
  },
  {
    name: "v-255b982b",
    path: "/tag/Arrays/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-255b982b").then(next)
    },
    meta: {"pid":"tags","id":"Arrays"}
  },
  {
    path: "/tag/Arrays/index.html",
    redirect: "/tag/Arrays/"
  },
  {
    name: "v-5f97b358",
    path: "/tag/Javascript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5f97b358").then(next)
    },
    meta: {"pid":"tags","id":"Javascript"}
  },
  {
    path: "/tag/Javascript/index.html",
    redirect: "/tag/Javascript/"
  },
  {
    name: "v-32383f72",
    path: "/tag/git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-32383f72").then(next)
    },
    meta: {"pid":"tags","id":"git"}
  },
  {
    path: "/tag/git/index.html",
    redirect: "/tag/git/"
  },
  {
    name: "v-4df76f3e",
    path: "/tag/Lambda/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-4df76f3e").then(next)
    },
    meta: {"pid":"tags","id":"Lambda"}
  },
  {
    path: "/tag/Lambda/index.html",
    redirect: "/tag/Lambda/"
  },
  {
    name: "v-d3a8c0a8",
    path: "/tag/Pinia/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-d3a8c0a8").then(next)
    },
    meta: {"pid":"tags","id":"Pinia"}
  },
  {
    path: "/tag/Pinia/index.html",
    redirect: "/tag/Pinia/"
  },
  {
    name: "v-54cc5f34",
    path: "/tag/SpringBoot/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-54cc5f34").then(next)
    },
    meta: {"pid":"tags","id":"SpringBoot"}
  },
  {
    path: "/tag/SpringBoot/index.html",
    redirect: "/tag/SpringBoot/"
  },
  {
    name: "v-325b9792",
    path: "/tag/AOP/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-325b9792").then(next)
    },
    meta: {"pid":"tags","id":"AOP"}
  },
  {
    path: "/tag/AOP/index.html",
    redirect: "/tag/AOP/"
  },
  {
    name: "v-bee809c0",
    path: "/tag/TypeScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-bee809c0").then(next)
    },
    meta: {"pid":"tags","id":"TypeScript"}
  },
  {
    path: "/tag/TypeScript/index.html",
    redirect: "/tag/TypeScript/"
  },
  {
    name: "v-32475d9a",
    path: "/tag/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-32475d9a").then(next)
    },
    meta: {"pid":"tags","id":"Vue"}
  },
  {
    path: "/tag/Vue/index.html",
    redirect: "/tag/Vue/"
  },
  {
    name: "v-21b69f93",
    path: "/tag/payment/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-21b69f93").then(next)
    },
    meta: {"pid":"tags","id":"payment"}
  },
  {
    path: "/tag/payment/index.html",
    redirect: "/tag/payment/"
  },
  {
    name: "v-d740cc78",
    path: "/tag/一切都刚刚好/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-d740cc78").then(next)
    },
    meta: {"pid":"tags","id":"一切都刚刚好"}
  },
  {
    path: "/tag/一切都刚刚好/index.html",
    redirect: "/tag/一切都刚刚好/"
  },
  {
    name: "v-5cfc18c5",
    path: "/categories/技术/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-5cfc18c5").then(next)
    },
    meta: {"pid":"categories","id":"技术"}
  },
  {
    path: "/categories/技术/index.html",
    redirect: "/categories/技术/"
  },
  {
    name: "v-5828c6a2",
    path: "/categories/专题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-5828c6a2").then(next)
    },
    meta: {"pid":"categories","id":"专题"}
  },
  {
    path: "/categories/专题/index.html",
    redirect: "/categories/专题/"
  },
  {
    name: "v-2e6b8ebc",
    path: "/categories/情感/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-2e6b8ebc").then(next)
    },
    meta: {"pid":"categories","id":"情感"}
  },
  {
    path: "/categories/情感/index.html",
    redirect: "/categories/情感/"
  },
  {
    name: "v-306a6f65",
    path: "/tag/Javascript/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-306a6f65").then(next)
    },
    meta: {"pid":"tags","id":"Javascript"}
  },
  {
    path: "/tag/Javascript/page/2/index.html",
    redirect: "/tag/Javascript/page/2/"
  },
  {
    name: "v-2c1a8558",
    path: "/categories/技术/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c1a8558").then(next)
    },
    meta: {"pid":"categories","id":"技术"}
  },
  {
    path: "/categories/技术/page/2/index.html",
    redirect: "/categories/技术/page/2/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]