/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\WebFontEnd\\Projects\\vuepress2-MyBlog-GitHub\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-b989fc08",
    path: "/BlogItem/DOM%E5%92%8CBOM%E6%95%99%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b989fc08").then(next)
    },
  },
  {
    path: "/BlogItem/DOM和BOM教程.html",
    redirect: "/BlogItem/DOM%E5%92%8CBOM%E6%95%99%E7%A8%8B.html"
  },
  {
    path: "/BlogItem/DOM和BOM教程.html",
    redirect: "/BlogItem/DOM%E5%92%8CBOM%E6%95%99%E7%A8%8B.html"
  },
  {
    name: "v-2c6800dc",
    path: "/BlogItem/Git%20%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c6800dc").then(next)
    },
  },
  {
    path: "/BlogItem/Git 基础教程.html",
    redirect: "/BlogItem/Git%20%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B.html"
  },
  {
    path: "/BlogItem/Git 基础教程.html",
    redirect: "/BlogItem/Git%20%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B.html"
  },
  {
    name: "v-bf439cc8",
    path: "/BlogItem/Mock.js%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bf439cc8").then(next)
    },
  },
  {
    path: "/BlogItem/Mock.js快速入门.html",
    redirect: "/BlogItem/Mock.js%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html"
  },
  {
    path: "/BlogItem/Mock.js快速入门.html",
    redirect: "/BlogItem/Mock.js%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html"
  },
  {
    name: "v-5feb51db",
    path: "/BlogItem/JavaScript%E8%BF%9B%E9%98%B6%E6%95%99%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5feb51db").then(next)
    },
  },
  {
    path: "/BlogItem/JavaScript进阶教程.html",
    redirect: "/BlogItem/JavaScript%E8%BF%9B%E9%98%B6%E6%95%99%E7%A8%8B.html"
  },
  {
    path: "/BlogItem/JavaScript进阶教程.html",
    redirect: "/BlogItem/JavaScript%E8%BF%9B%E9%98%B6%E6%95%99%E7%A8%8B.html"
  },
  {
    name: "v-569e6d68",
    path: "/BlogItem/Pinia%E5%85%A5%E9%97%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-569e6d68").then(next)
    },
  },
  {
    path: "/BlogItem/Pinia入门.html",
    redirect: "/BlogItem/Pinia%E5%85%A5%E9%97%A8.html"
  },
  {
    path: "/BlogItem/Pinia入门.html",
    redirect: "/BlogItem/Pinia%E5%85%A5%E9%97%A8.html"
  },
  {
    name: "v-4bb02f54",
    path: "/BlogItem/TypeScript%E8%BF%9B%E9%98%B6%E8%AF%AD%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4bb02f54").then(next)
    },
  },
  {
    path: "/BlogItem/TypeScript进阶语法.html",
    redirect: "/BlogItem/TypeScript%E8%BF%9B%E9%98%B6%E8%AF%AD%E6%B3%95.html"
  },
  {
    path: "/BlogItem/TypeScript进阶语法.html",
    redirect: "/BlogItem/TypeScript%E8%BF%9B%E9%98%B6%E8%AF%AD%E6%B3%95.html"
  },
  {
    name: "v-23bace5a",
    path: "/BlogItem/TypeScript%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23bace5a").then(next)
    },
  },
  {
    path: "/BlogItem/TypeScript基础语法.html",
    redirect: "/BlogItem/TypeScript%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html"
  },
  {
    path: "/BlogItem/TypeScript基础语法.html",
    redirect: "/BlogItem/TypeScript%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html"
  },
  {
    name: "v-59022ba9",
    path: "/BlogItem/vue3%20%E2%85%A0%20vue%20%E5%9F%BA%E7%A1%80%E5%85%A5%E9%97%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59022ba9").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅰ vue 基础入门.html",
    redirect: "/BlogItem/vue3%20%E2%85%A0%20vue%20%E5%9F%BA%E7%A1%80%E5%85%A5%E9%97%A8.html"
  },
  {
    path: "/BlogItem/vue3 Ⅰ vue 基础入门.html",
    redirect: "/BlogItem/vue3%20%E2%85%A0%20vue%20%E5%9F%BA%E7%A1%80%E5%85%A5%E9%97%A8.html"
  },
  {
    name: "v-3d71b92c",
    path: "/BlogItem/vue3%20%E2%85%A1%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8A%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d71b92c").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅱ vue 组件基础（上）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A1%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8A%EF%BC%89.html"
  },
  {
    path: "/BlogItem/vue3 Ⅱ vue 组件基础（上）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A1%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8A%EF%BC%89.html"
  },
  {
    name: "v-4f4a33ac",
    path: "/BlogItem/vue3%20%E2%85%A2%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8B%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f4a33ac").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅲ vue 组件基础（下）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A2%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8B%EF%BC%89.html"
  },
  {
    path: "/BlogItem/vue3 Ⅲ vue 组件基础（下）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A2%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8B%EF%BC%89.html"
  },
  {
    name: "v-0042273c",
    path: "/BlogItem/vue3%20%E2%85%A3%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8A%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0042273c").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅳ vue 组件高级（上）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A3%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8A%EF%BC%89.html"
  },
  {
    path: "/BlogItem/vue3 Ⅳ vue 组件高级（上）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A3%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8A%EF%BC%89.html"
  },
  {
    name: "v-69a93fb5",
    path: "/BlogItem/vue3%20%E2%85%A5%20vue%20%E8%B7%AF%E7%94%B1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69a93fb5").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅵ vue 路由.html",
    redirect: "/BlogItem/vue3%20%E2%85%A5%20vue%20%E8%B7%AF%E7%94%B1.html"
  },
  {
    path: "/BlogItem/vue3 Ⅵ vue 路由.html",
    redirect: "/BlogItem/vue3%20%E2%85%A5%20vue%20%E8%B7%AF%E7%94%B1.html"
  },
  {
    name: "v-11b766e2",
    path: "/BlogItem/vue3%20%E2%85%A4%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8B%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-11b766e2").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅴ vue 组件高级（下）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A4%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8B%EF%BC%89.html"
  },
  {
    path: "/BlogItem/vue3 Ⅴ vue 组件高级（下）.html",
    redirect: "/BlogItem/vue3%20%E2%85%A4%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8B%EF%BC%89.html"
  },
  {
    name: "v-a0ae85ba",
    path: "/BlogItem/Node.js%E6%95%99%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a0ae85ba").then(next)
    },
  },
  {
    path: "/BlogItem/Node.js教程.html",
    redirect: "/BlogItem/Node.js%E6%95%99%E7%A8%8B.html"
  },
  {
    path: "/BlogItem/Node.js教程.html",
    redirect: "/BlogItem/Node.js%E6%95%99%E7%A8%8B.html"
  },
  {
    name: "v-53f6806d",
    path: "/BlogItem/SpringBootWeb%20-%20AOP.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53f6806d").then(next)
    },
  },
  {
    path: "/BlogItem/SpringBootWeb - AOP.html",
    redirect: "/BlogItem/SpringBootWeb%20-%20AOP.html"
  },
  {
    path: "/BlogItem/SpringBootWeb - AOP.html",
    redirect: "/BlogItem/SpringBootWeb%20-%20AOP.html"
  },
  {
    name: "v-0907000a",
    path: "/BlogItem/vue3%20%E2%85%A6%20vue%20%E8%A1%A5%E5%85%85%E5%86%85%E5%AE%B9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0907000a").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅶ vue 补充内容.html",
    redirect: "/BlogItem/vue3%20%E2%85%A6%20vue%20%E8%A1%A5%E5%85%85%E5%86%85%E5%AE%B9.html"
  },
  {
    path: "/BlogItem/vue3 Ⅶ vue 补充内容.html",
    redirect: "/BlogItem/vue3%20%E2%85%A6%20vue%20%E8%A1%A5%E5%85%85%E5%86%85%E5%AE%B9.html"
  },
  {
    name: "v-0074a62e",
    path: "/BlogItem/%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0074a62e").then(next)
    },
  },
  {
    path: "/BlogItem/微信支付.html",
    redirect: "/BlogItem/%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98.html"
  },
  {
    path: "/BlogItem/微信支付.html",
    redirect: "/BlogItem/%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98.html"
  },
  {
    name: "v-16c2594c",
    path: "/BlogItem/vue3%20%E2%85%A7%20vue%20%E5%B8%B8%E8%A7%81%E4%BC%98%E5%8C%96%E6%89%8B%E6%AE%B5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16c2594c").then(next)
    },
  },
  {
    path: "/BlogItem/vue3 Ⅷ vue 常见优化手段.html",
    redirect: "/BlogItem/vue3%20%E2%85%A7%20vue%20%E5%B8%B8%E8%A7%81%E4%BC%98%E5%8C%96%E6%89%8B%E6%AE%B5.html"
  },
  {
    path: "/BlogItem/vue3 Ⅷ vue 常见优化手段.html",
    redirect: "/BlogItem/vue3%20%E2%85%A7%20vue%20%E5%B8%B8%E8%A7%81%E4%BC%98%E5%8C%96%E6%89%8B%E6%AE%B5.html"
  },
  {
    name: "v-713197fe",
    path: "/BlogItem/vue3%E4%B8%8E%E7%BB%84%E5%90%88%E5%BC%8FAPI.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-713197fe").then(next)
    },
  },
  {
    path: "/BlogItem/vue3与组合式API.html",
    redirect: "/BlogItem/vue3%E4%B8%8E%E7%BB%84%E5%90%88%E5%BC%8FAPI.html"
  },
  {
    path: "/BlogItem/vue3与组合式API.html",
    redirect: "/BlogItem/vue3%E4%B8%8E%E7%BB%84%E5%90%88%E5%BC%8FAPI.html"
  },
  {
    name: "v-1e26d155",
    path: "/BlogItem/%E6%88%91%E4%BB%AC%E7%9A%84%E6%95%85%E4%BA%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e26d155").then(next)
    },
  },
  {
    path: "/BlogItem/我们的故事.html",
    redirect: "/BlogItem/%E6%88%91%E4%BB%AC%E7%9A%84%E6%95%85%E4%BA%8B.html"
  },
  {
    path: "/BlogItem/我们的故事.html",
    redirect: "/BlogItem/%E6%88%91%E4%BB%AC%E7%9A%84%E6%95%85%E4%BA%8B.html"
  },
  {
    name: "v-f00b49ce",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f00b49ce").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7ee369b8",
    path: "/BlogItem/%E8%B7%AF%E5%BE%84%E5%88%AB%E5%90%8D%20ElementPlus%20Sass%E9%85%8D%E7%BD%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ee369b8").then(next)
    },
  },
  {
    path: "/BlogItem/路径别名 ElementPlus Sass配置.html",
    redirect: "/BlogItem/%E8%B7%AF%E5%BE%84%E5%88%AB%E5%90%8D%20ElementPlus%20Sass%E9%85%8D%E7%BD%AE.html"
  },
  {
    path: "/BlogItem/路径别名 ElementPlus Sass配置.html",
    redirect: "/BlogItem/%E8%B7%AF%E5%BE%84%E5%88%AB%E5%90%8D%20ElementPlus%20Sass%E9%85%8D%E7%BD%AE.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-5f97b358",
    path: "/tag/Javascript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5f97b358").then(next)
    },
    meta: {"pid":"tags","id":"Javascript"}
  },
  {
    path: "/tag/Javascript/index.html",
    redirect: "/tag/Javascript/"
  },
  {
    name: "v-32383f72",
    path: "/tag/git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-32383f72").then(next)
    },
    meta: {"pid":"tags","id":"git"}
  },
  {
    path: "/tag/git/index.html",
    redirect: "/tag/git/"
  },
  {
    name: "v-d3a8c0a8",
    path: "/tag/Pinia/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-d3a8c0a8").then(next)
    },
    meta: {"pid":"tags","id":"Pinia"}
  },
  {
    path: "/tag/Pinia/index.html",
    redirect: "/tag/Pinia/"
  },
  {
    name: "v-bee809c0",
    path: "/tag/TypeScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-bee809c0").then(next)
    },
    meta: {"pid":"tags","id":"TypeScript"}
  },
  {
    path: "/tag/TypeScript/index.html",
    redirect: "/tag/TypeScript/"
  },
  {
    name: "v-32475d9a",
    path: "/tag/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-32475d9a").then(next)
    },
    meta: {"pid":"tags","id":"Vue"}
  },
  {
    path: "/tag/Vue/index.html",
    redirect: "/tag/Vue/"
  },
  {
    name: "v-18082c7a",
    path: "/tag/Java/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-18082c7a").then(next)
    },
    meta: {"pid":"tags","id":"Java"}
  },
  {
    path: "/tag/Java/index.html",
    redirect: "/tag/Java/"
  },
  {
    name: "v-54cc5f34",
    path: "/tag/SpringBoot/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-54cc5f34").then(next)
    },
    meta: {"pid":"tags","id":"SpringBoot"}
  },
  {
    path: "/tag/SpringBoot/index.html",
    redirect: "/tag/SpringBoot/"
  },
  {
    name: "v-325b9792",
    path: "/tag/AOP/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-325b9792").then(next)
    },
    meta: {"pid":"tags","id":"AOP"}
  },
  {
    path: "/tag/AOP/index.html",
    redirect: "/tag/AOP/"
  },
  {
    name: "v-21b69f93",
    path: "/tag/payment/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-21b69f93").then(next)
    },
    meta: {"pid":"tags","id":"payment"}
  },
  {
    path: "/tag/payment/index.html",
    redirect: "/tag/payment/"
  },
  {
    name: "v-d740cc78",
    path: "/tag/一切都刚刚好/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-d740cc78").then(next)
    },
    meta: {"pid":"tags","id":"一切都刚刚好"}
  },
  {
    path: "/tag/一切都刚刚好/index.html",
    redirect: "/tag/一切都刚刚好/"
  },
  {
    name: "v-5cfc18c5",
    path: "/categories/技术/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-5cfc18c5").then(next)
    },
    meta: {"pid":"categories","id":"技术"}
  },
  {
    path: "/categories/技术/index.html",
    redirect: "/categories/技术/"
  },
  {
    name: "v-5828c6a2",
    path: "/categories/专题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-5828c6a2").then(next)
    },
    meta: {"pid":"categories","id":"专题"}
  },
  {
    path: "/categories/专题/index.html",
    redirect: "/categories/专题/"
  },
  {
    name: "v-2e6b8ebc",
    path: "/categories/情感/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-2e6b8ebc").then(next)
    },
    meta: {"pid":"categories","id":"情感"}
  },
  {
    path: "/categories/情感/index.html",
    redirect: "/categories/情感/"
  },
  {
    name: "v-306a6f65",
    path: "/tag/Javascript/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-306a6f65").then(next)
    },
    meta: {"pid":"tags","id":"Javascript"}
  },
  {
    path: "/tag/Javascript/page/2/index.html",
    redirect: "/tag/Javascript/page/2/"
  },
  {
    name: "v-2c1a8558",
    path: "/categories/技术/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c1a8558").then(next)
    },
    meta: {"pid":"categories","id":"技术"}
  },
  {
    path: "/categories/技术/page/2/index.html",
    redirect: "/categories/技术/page/2/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]