/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "IndulgeBack",
  "description": "May there be enough clouds in your life to make a beautiful sunset.",
  "base": "/",
  "headTags": [
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ],
    [
      "link",
      {
        "rel": "icon",
        "href": "/logo.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "Java中Arrays的静态方法",
      "frontmatter": {
        "title": "Java中Arrays的静态方法",
        "date": "2023-09-19T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Java",
          "Arrays"
        ]
      },
      "regularPath": "/BlogItem/Arrays%E7%9A%84%E9%9D%99%E6%80%81%E6%96%B9%E6%B3%95.html",
      "relativePath": "BlogItem/Arrays的静态方法.md",
      "key": "v-3e68fda2",
      "path": "/BlogItem/Arrays%E7%9A%84%E9%9D%99%E6%80%81%E6%96%B9%E6%B3%95.html",
      "headers": [
        {
          "level": 3,
          "title": "1.tostring",
          "slug": "_1-tostring"
        },
        {
          "level": 3,
          "title": "2.binarySearch",
          "slug": "_2-binarysearch"
        },
        {
          "level": 3,
          "title": "3.copyOf",
          "slug": "_3-copyof"
        },
        {
          "level": 3,
          "title": "4.copyOfRange",
          "slug": "_4-copyofrange"
        },
        {
          "level": 3,
          "title": "5.fill",
          "slug": "_5-fill"
        },
        {
          "level": 3,
          "title": "6.sort",
          "slug": "_6-sort"
        },
        {
          "level": 3,
          "title": "7.重载的sort方法",
          "slug": "_7-重载的sort方法"
        }
      ],
      "size": "2.32kb"
    },
    {
      "title": "IDEA 常用快捷键",
      "frontmatter": {
        "title": "IDEA 常用快捷键",
        "date": "2023-09-21T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "技巧"
        ],
        "tags": [
          "IDEA"
        ]
      },
      "regularPath": "/BlogItem/IDEA%E5%B8%B8%E7%94%A8%E5%BF%AB%E6%8D%B7%E9%94%AE.html",
      "relativePath": "BlogItem/IDEA常用快捷键.md",
      "key": "v-dee8eb26",
      "path": "/BlogItem/IDEA%E5%B8%B8%E7%94%A8%E5%BF%AB%E6%8D%B7%E9%94%AE.html",
      "headers": [
        {
          "level": 3,
          "title": "日常使用",
          "slug": "日常使用"
        },
        {
          "level": 3,
          "title": "System.out",
          "slug": "system-out"
        },
        {
          "level": 3,
          "title": "查找",
          "slug": "查找"
        },
        {
          "level": 3,
          "title": "跳转切换",
          "slug": "跳转切换"
        },
        {
          "level": 3,
          "title": "编码相关",
          "slug": "编码相关"
        },
        {
          "level": 3,
          "title": "代码阅读相关",
          "slug": "代码阅读相关"
        },
        {
          "level": 3,
          "title": "版本管理相关",
          "slug": "版本管理相关"
        }
      ],
      "size": "6.06kb"
    },
    {
      "title": "Git 基础教程",
      "frontmatter": {
        "title": "Git 基础教程",
        "date": "2023-07-01T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "git"
        ]
      },
      "regularPath": "/BlogItem/Git%20%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B.html",
      "relativePath": "BlogItem/Git 基础教程.md",
      "key": "v-af2edb96",
      "path": "/BlogItem/Git%20%E5%9F%BA%E7%A1%80%E6%95%99%E7%A8%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "01.Git 初识",
          "slug": "_01-git-初识"
        },
        {
          "level": 2,
          "title": "02.Git 仓库",
          "slug": "_02-git-仓库"
        },
        {
          "level": 2,
          "title": "03.Git 的三个区域",
          "slug": "_03-git-的三个区域"
        },
        {
          "level": 2,
          "title": "04.Git 文件状态",
          "slug": "_04-git-文件状态"
        },
        {
          "level": 2,
          "title": "05.Git 暂存区作用",
          "slug": "_05-git-暂存区作用"
        },
        {
          "level": 2,
          "title": "06.Git-切换版本",
          "slug": "_06-git-切换版本"
        },
        {
          "level": 2,
          "title": "07.删除文件",
          "slug": "_07-删除文件"
        },
        {
          "level": 2,
          "title": "08.忽略文件",
          "slug": "_08-忽略文件"
        },
        {
          "level": 2,
          "title": "09.分支的概念",
          "slug": "_09-分支的概念"
        },
        {
          "level": 2,
          "title": "10.练习-登录 bug 修复",
          "slug": "_10-练习-登录-bug-修复"
        },
        {
          "level": 2,
          "title": "11.分支-合并与删除",
          "slug": "_11-分支-合并与删除"
        },
        {
          "level": 2,
          "title": "12.分支-合并与提交",
          "slug": "_12-分支-合并与提交"
        },
        {
          "level": 2,
          "title": "13.分支-合并冲突",
          "slug": "_13-分支-合并冲突"
        },
        {
          "level": 2,
          "title": "14.Git 常用命令",
          "slug": "_14-git-常用命令"
        },
        {
          "level": 2,
          "title": "15.Git 远程仓库",
          "slug": "_15-git-远程仓库"
        },
        {
          "level": 2,
          "title": "16.Git 远程仓库 - 克隆",
          "slug": "_16-git-远程仓库-克隆"
        },
        {
          "level": 2,
          "title": "17.多人协同开发",
          "slug": "_17-多人协同开发"
        },
        {
          "level": 2,
          "title": "18.VSCode 中使用 Git",
          "slug": "_18-vscode-中使用-git"
        },
        {
          "level": 2,
          "title": "19.Git 常用命令",
          "slug": "_19-git-常用命令"
        }
      ],
      "size": "7.95kb"
    },
    {
      "title": "DOM和BOM操作的整合",
      "frontmatter": {
        "title": "DOM和BOM操作的整合",
        "date": "2023-04-02T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Javascript"
        ]
      },
      "regularPath": "/BlogItem/DOM%E5%92%8CBOM%E6%95%99%E7%A8%8B.html",
      "relativePath": "BlogItem/DOM和BOM教程.md",
      "key": "v-03ea0756",
      "path": "/BlogItem/DOM%E5%92%8CBOM%E6%95%99%E7%A8%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "Ⅰ、DOM",
          "slug": "i、dom"
        },
        {
          "level": 2,
          "title": "一、DOM操作",
          "slug": "一、dom操作"
        },
        {
          "level": 3,
          "title": "1.根据css选择器来获取DOM元素",
          "slug": "_1-根据css选择器来获取dom元素"
        },
        {
          "level": 3,
          "title": "2.其他获取DOM元素的方法",
          "slug": "_2-其他获取dom元素的方法"
        },
        {
          "level": 3,
          "title": "3.操作元素内容",
          "slug": "_3-操作元素内容"
        },
        {
          "level": 3,
          "title": "4.操作元素属性",
          "slug": "_4-操作元素属性"
        },
        {
          "level": 3,
          "title": "5.操作元素样式属性",
          "slug": "_5-操作元素样式属性"
        },
        {
          "level": 3,
          "title": "6.通过classList修改样式",
          "slug": "_6-通过classlist修改样式"
        },
        {
          "level": 3,
          "title": "7.操作表单元素属性",
          "slug": "_7-操作表单元素属性"
        },
        {
          "level": 3,
          "title": "8.自定义属性",
          "slug": "_8-自定义属性"
        },
        {
          "level": 3,
          "title": "9.定时器 - 间歇函数",
          "slug": "_9-定时器-间歇函数"
        },
        {
          "level": 2,
          "title": "二、DOM事件",
          "slug": "二、dom事件"
        },
        {
          "level": 3,
          "title": "1.事件监听",
          "slug": "_1-事件监听"
        },
        {
          "level": 3,
          "title": "2.addEventListener与on区别",
          "slug": "_2-addeventlistener与on区别"
        },
        {
          "level": 3,
          "title": "3.事件",
          "slug": "_3-事件"
        },
        {
          "level": 3,
          "title": "4.事件对象及其位置",
          "slug": "_4-事件对象及其位置"
        },
        {
          "level": 3,
          "title": "5事件对象中的常用属性",
          "slug": "_5事件对象中的常用属性"
        },
        {
          "level": 3,
          "title": "6.trim()去除字符串左右的空格",
          "slug": "_6-trim-去除字符串左右的空格"
        },
        {
          "level": 3,
          "title": "7.环境对象",
          "slug": "_7-环境对象"
        },
        {
          "level": 3,
          "title": "8.回调函数",
          "slug": "_8-回调函数"
        },
        {
          "level": 3,
          "title": "9.捕获和冒泡",
          "slug": "_9-捕获和冒泡"
        },
        {
          "level": 3,
          "title": "10.阻止冒泡",
          "slug": "_10-阻止冒泡"
        },
        {
          "level": 2,
          "title": "三、事件委托",
          "slug": "三、事件委托"
        },
        {
          "level": 2,
          "title": "四、其他事件",
          "slug": "四、其他事件"
        },
        {
          "level": 3,
          "title": "1.页面加载事件",
          "slug": "_1-页面加载事件"
        },
        {
          "level": 3,
          "title": "2.元素滚动事件",
          "slug": "_2-元素滚动事件"
        },
        {
          "level": 3,
          "title": "3.页面尺寸事件",
          "slug": "_3-页面尺寸事件"
        },
        {
          "level": 2,
          "title": "五、日期对象",
          "slug": "五、日期对象"
        },
        {
          "level": 3,
          "title": "1.实例化",
          "slug": "_1-实例化"
        },
        {
          "level": 3,
          "title": "2.方法",
          "slug": "_2-方法"
        },
        {
          "level": 3,
          "title": "3.时间戳",
          "slug": "_3-时间戳"
        },
        {
          "level": 2,
          "title": "六、DOM 节点",
          "slug": "六、dom-节点"
        },
        {
          "level": 3,
          "title": "1.插入节点",
          "slug": "_1-插入节点"
        },
        {
          "level": 3,
          "title": "2.删除节点",
          "slug": "_2-删除节点"
        },
        {
          "level": 3,
          "title": "3.查找节点",
          "slug": "_3-查找节点"
        },
        {
          "level": 2,
          "title": "Ⅱ、BOM",
          "slug": "ii、bom"
        },
        {
          "level": 2,
          "title": "一、window对象",
          "slug": "一、window对象"
        },
        {
          "level": 2,
          "title": "二、定时器-延迟函数",
          "slug": "二、定时器-延迟函数"
        },
        {
          "level": 2,
          "title": "三、location对象",
          "slug": "三、location对象"
        },
        {
          "level": 2,
          "title": "四、navigator对象",
          "slug": "四、navigator对象"
        },
        {
          "level": 2,
          "title": "五、histroy对象",
          "slug": "五、histroy对象"
        },
        {
          "level": 2,
          "title": "六、本地存储（重点）",
          "slug": "六、本地存储-重点"
        },
        {
          "level": 3,
          "title": "1.localStorage（重点）",
          "slug": "_1-localstorage-重点"
        },
        {
          "level": 3,
          "title": "2.sessionStorage（了解）",
          "slug": "_2-sessionstorage-了解"
        },
        {
          "level": 3,
          "title": "3.localStorage 存储复杂数据类型",
          "slug": "_3-localstorage-存储复杂数据类型"
        },
        {
          "level": 2,
          "title": "七、综合案例",
          "slug": "七、综合案例"
        },
        {
          "level": 3,
          "title": "1.数组map 方法",
          "slug": "_1-数组map-方法"
        },
        {
          "level": 3,
          "title": "2.数组join方法",
          "slug": "_2-数组join方法"
        },
        {
          "level": 2,
          "title": "Ⅲ、正则表达式",
          "slug": "iii、正则表达式"
        },
        {
          "level": 3,
          "title": "一、正则基本使用",
          "slug": "一、正则基本使用"
        },
        {
          "level": 3,
          "title": "二、元字符",
          "slug": "二、元字符"
        },
        {
          "level": 3,
          "title": "三、替换和修饰符",
          "slug": "三、替换和修饰符"
        }
      ],
      "size": "31.07kb"
    },
    {
      "title": "JavaScript 进阶教程",
      "frontmatter": {
        "title": "JavaScript 进阶教程",
        "date": "2023-04-08T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Javascript"
        ]
      },
      "regularPath": "/BlogItem/JavaScript%E8%BF%9B%E9%98%B6%E6%95%99%E7%A8%8B.html",
      "relativePath": "BlogItem/JavaScript进阶教程.md",
      "key": "v-28acc7f4",
      "path": "/BlogItem/JavaScript%E8%BF%9B%E9%98%B6%E6%95%99%E7%A8%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "一、作用域",
          "slug": "一、作用域"
        },
        {
          "level": 3,
          "title": "1.局部作用域",
          "slug": "_1-局部作用域"
        },
        {
          "level": 3,
          "title": "2.全局作用域",
          "slug": "_2-全局作用域"
        },
        {
          "level": 3,
          "title": "3.作用域链",
          "slug": "_3-作用域链"
        },
        {
          "level": 3,
          "title": "4.闭包",
          "slug": "_4-闭包"
        },
        {
          "level": 3,
          "title": "5.变量提升",
          "slug": "_5-变量提升"
        },
        {
          "level": 2,
          "title": "二、函数",
          "slug": "二、函数"
        },
        {
          "level": 3,
          "title": "1.函数提升",
          "slug": "_1-函数提升"
        },
        {
          "level": 3,
          "title": "2.函数参数",
          "slug": "_2-函数参数"
        },
        {
          "level": 3,
          "title": "3.箭头函数",
          "slug": "_3-箭头函数"
        },
        {
          "level": 2,
          "title": "三、解构赋值",
          "slug": "三、解构赋值"
        },
        {
          "level": 3,
          "title": "1.数组解构",
          "slug": "_1-数组解构"
        },
        {
          "level": 3,
          "title": "2.对象解构",
          "slug": "_2-对象解构"
        },
        {
          "level": 2,
          "title": "四、综合案例",
          "slug": "四、综合案例"
        },
        {
          "level": 3,
          "title": "1.forEach遍历数组",
          "slug": "_1-foreach遍历数组"
        },
        {
          "level": 3,
          "title": "2.filter筛选数组",
          "slug": "_2-filter筛选数组"
        },
        {
          "level": 2,
          "title": "五、深入对象",
          "slug": "五、深入对象"
        },
        {
          "level": 3,
          "title": "1.构造函数",
          "slug": "_1-构造函数"
        },
        {
          "level": 3,
          "title": "2.实例成员",
          "slug": "_2-实例成员"
        },
        {
          "level": 3,
          "title": "3.静态成员",
          "slug": "_3-静态成员"
        },
        {
          "level": 2,
          "title": "六、内置构造函数",
          "slug": "六、内置构造函数"
        },
        {
          "level": 3,
          "title": "1.Object",
          "slug": "_1-object"
        },
        {
          "level": 3,
          "title": "2.Array",
          "slug": "_2-array"
        },
        {
          "level": 3,
          "title": "3.包装类型",
          "slug": "_3-包装类型"
        },
        {
          "level": 2,
          "title": "七、编程思想",
          "slug": "七、编程思想"
        },
        {
          "level": 3,
          "title": "1.面向过程",
          "slug": "_1-面向过程"
        },
        {
          "level": 3,
          "title": "2.面向对象",
          "slug": "_2-面向对象"
        },
        {
          "level": 2,
          "title": "八、构造函数",
          "slug": "八、构造函数"
        },
        {
          "level": 2,
          "title": "九、原型对象",
          "slug": "九、原型对象"
        },
        {
          "level": 3,
          "title": "1.constructor 属性",
          "slug": "_1-constructor-属性"
        },
        {
          "level": 3,
          "title": "2.对象原型",
          "slug": "_2-对象原型"
        },
        {
          "level": 3,
          "title": "3.原型继承",
          "slug": "_3-原型继承"
        },
        {
          "level": 3,
          "title": "4.原型链",
          "slug": "_4-原型链"
        },
        {
          "level": 2,
          "title": "十、深浅拷贝",
          "slug": "十、深浅拷贝"
        },
        {
          "level": 3,
          "title": "1.浅拷贝",
          "slug": "_1-浅拷贝"
        },
        {
          "level": 3,
          "title": "2.深拷贝",
          "slug": "_2-深拷贝"
        },
        {
          "level": 2,
          "title": "十一、异常处理",
          "slug": "十一、异常处理"
        },
        {
          "level": 3,
          "title": "1.throw",
          "slug": "_1-throw"
        },
        {
          "level": 3,
          "title": "2.try ... catch",
          "slug": "_2-try-catch"
        },
        {
          "level": 3,
          "title": "3.debugger",
          "slug": "_3-debugger"
        },
        {
          "level": 2,
          "title": "十二、处理this",
          "slug": "十二、处理this"
        },
        {
          "level": 3,
          "title": "1.普通函数",
          "slug": "_1-普通函数"
        },
        {
          "level": 3,
          "title": "2.箭头函数",
          "slug": "_2-箭头函数"
        },
        {
          "level": 3,
          "title": "3.改变this指向",
          "slug": "_3-改变this指向"
        },
        {
          "level": 2,
          "title": "十三、防抖节流",
          "slug": "十三、防抖节流"
        },
        {
          "level": 3,
          "title": "1.防抖（debounce）",
          "slug": "_1-防抖-debounce"
        },
        {
          "level": 3,
          "title": "2.节流（throttle）",
          "slug": "_2-节流-throttle"
        }
      ],
      "size": "34.72kb"
    },
    {
      "title": "Lambda 表达式",
      "frontmatter": {
        "title": "Lambda 表达式",
        "date": "2023-09-19T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "专题"
        ],
        "tags": [
          "Java",
          "Lambda"
        ]
      },
      "regularPath": "/BlogItem/Lambda%20%E8%A1%A8%E8%BE%BE%E5%BC%8F.html",
      "relativePath": "BlogItem/Lambda 表达式.md",
      "key": "v-1de00e7b",
      "path": "/BlogItem/Lambda%20%E8%A1%A8%E8%BE%BE%E5%BC%8F.html",
      "headers": [
        {
          "level": 3,
          "title": "1.Lambda表达式的标准格式",
          "slug": "_1-lambda表达式的标准格式"
        },
        {
          "level": 3,
          "title": "2.Lambda 表达式的具体使用场景",
          "slug": "_2-lambda-表达式的具体使用场景"
        },
        {
          "level": 3,
          "title": "3.Lambda 表达式的省略规则",
          "slug": "_3-lambda-表达式的省略规则"
        },
        {
          "level": 3,
          "title": "4.Lambda 表达式使用示例",
          "slug": "_4-lambda-表达式使用示例"
        }
      ],
      "size": "1.66kb"
    },
    {
      "title": "Mock.js快速入门",
      "frontmatter": {
        "title": "Mock.js快速入门",
        "date": "2023-09-12T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "专题"
        ],
        "tags": [
          "Javascript"
        ]
      },
      "regularPath": "/BlogItem/Mock.js%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html",
      "relativePath": "BlogItem/Mock.js快速入门.md",
      "key": "v-1c946e75",
      "path": "/BlogItem/Mock.js%E5%BF%AB%E9%80%9F%E5%85%A5%E9%97%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "一、什么是Mock.js",
          "slug": "一、什么是mock-js"
        },
        {
          "level": 2,
          "title": "二、安装 Mock.js",
          "slug": "二、安装-mock-js"
        },
        {
          "level": 3,
          "title": "1.通过 npm 安装 Mock.js",
          "slug": "_1-通过-npm-安装-mock-js"
        },
        {
          "level": 3,
          "title": "2.通过 yarn 安装 Mock.js",
          "slug": "_2-通过-yarn-安装-mock-js"
        },
        {
          "level": 3,
          "title": "3.通过 pnpm 安装 Mock.js",
          "slug": "_3-通过-pnpm-安装-mock-js"
        },
        {
          "level": 2,
          "title": "三、使用 Mock.js",
          "slug": "三、使用-mock-js"
        },
        {
          "level": 2,
          "title": "四、使用 Mock 生成数据的语法",
          "slug": "四、使用-mock-生成数据的语法"
        },
        {
          "level": 3,
          "title": "1.生成指定类型",
          "slug": "_1-生成指定类型"
        },
        {
          "level": 3,
          "title": "2.生成文字",
          "slug": "_2-生成文字"
        },
        {
          "level": 3,
          "title": "3.生成增量id",
          "slug": "_3-生成增量id"
        },
        {
          "level": 3,
          "title": "4.生成姓名-地址-身份证号",
          "slug": "_4-生成姓名-地址-身份证号"
        },
        {
          "level": 3,
          "title": "5.生成随机图片",
          "slug": "_5-生成随机图片"
        },
        {
          "level": 3,
          "title": "6.生成时间",
          "slug": "_6-生成时间"
        },
        {
          "level": 3,
          "title": "7.生成列表",
          "slug": "_7-生成列表"
        },
        {
          "level": 2,
          "title": "五、使用 Mock 拦截请求",
          "slug": "五、使用-mock-拦截请求"
        },
        {
          "level": 3,
          "title": "1.定义拦截 GET 请求",
          "slug": "_1-定义拦截-get-请求"
        },
        {
          "level": 3,
          "title": "2.定义拦截 POST 请求",
          "slug": "_2-定义拦截-post-请求"
        },
        {
          "level": 3,
          "title": "3.回调函数形式",
          "slug": "_3-回调函数形式"
        },
        {
          "level": 3,
          "title": "4.请求的接口地址可以使用正则表达式",
          "slug": "_4-请求的接口地址可以使用正则表达式"
        },
        {
          "level": 3,
          "title": "5.自定义函数获取url中的参数",
          "slug": "_5-自定义函数获取url中的参数"
        },
        {
          "level": 3,
          "title": "6.获取 POST 请求中的 body",
          "slug": "_6-获取-post-请求中的-body"
        }
      ],
      "size": "4.82kb"
    },
    {
      "title": "Pinia入门",
      "frontmatter": {
        "title": "Pinia入门",
        "date": "2023-5-20",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Pinia"
        ]
      },
      "regularPath": "/BlogItem/Pinia%E5%85%A5%E9%97%A8.html",
      "relativePath": "BlogItem/Pinia入门.md",
      "key": "v-76aa7db6",
      "path": "/BlogItem/Pinia%E5%85%A5%E9%97%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "什么是pinia",
          "slug": "什么是pinia"
        },
        {
          "level": 2,
          "title": "创建空Vue项目并安装Pinia",
          "slug": "创建空vue项目并安装pinia"
        },
        {
          "level": 3,
          "title": "1. 创建空Vue项目",
          "slug": "_1-创建空vue项目"
        },
        {
          "level": 3,
          "title": "2. 安装Pinia并注册",
          "slug": "_2-安装pinia并注册"
        },
        {
          "level": 2,
          "title": "实现counter",
          "slug": "实现counter"
        },
        {
          "level": 3,
          "title": "1- 定义store",
          "slug": "_1-定义store"
        },
        {
          "level": 3,
          "title": "2- 组件使用store",
          "slug": "_2-组件使用store"
        },
        {
          "level": 2,
          "title": "实现getters",
          "slug": "实现getters"
        },
        {
          "level": 2,
          "title": "异步action",
          "slug": "异步action"
        },
        {
          "level": 3,
          "title": "1- store中定义action",
          "slug": "_1-store中定义action"
        },
        {
          "level": 3,
          "title": "2- 组件中调用action",
          "slug": "_2-组件中调用action"
        },
        {
          "level": 2,
          "title": "storeToRefs保持响应式解构",
          "slug": "storetorefs保持响应式解构"
        }
      ],
      "size": "2.76kb"
    },
    {
      "title": "SpringBootWeb - AOP",
      "frontmatter": {
        "title": "SpringBootWeb - AOP",
        "date": "2023-9-14",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Java",
          "SpringBoot",
          "AOP"
        ]
      },
      "regularPath": "/BlogItem/SpringBootWeb%20-%20AOP.html",
      "relativePath": "BlogItem/SpringBootWeb - AOP.md",
      "key": "v-a2730a74",
      "path": "/BlogItem/SpringBootWeb%20-%20AOP.html",
      "headers": [
        {
          "level": 2,
          "title": "一、AOP 概述",
          "slug": "一、aop-概述"
        },
        {
          "level": 3,
          "title": "1.什么是AOP？",
          "slug": "_1-什么是aop"
        },
        {
          "level": 3,
          "title": "2.AOP快速入门",
          "slug": "_2-aop快速入门"
        },
        {
          "level": 3,
          "title": "3.AOP核心概念",
          "slug": "_3-aop核心概念"
        },
        {
          "level": 2,
          "title": "二、AOP进阶",
          "slug": "二、aop进阶"
        },
        {
          "level": 3,
          "title": "1 通知类型",
          "slug": "_1-通知类型"
        },
        {
          "level": 3,
          "title": "2 通知顺序",
          "slug": "_2-通知顺序"
        },
        {
          "level": 3,
          "title": "3 切入点表达式",
          "slug": "_3-切入点表达式"
        },
        {
          "level": 3,
          "title": "4 连接点",
          "slug": "_4-连接点"
        }
      ],
      "size": "17.61kb"
    },
    {
      "title": "TypeScript 基础语法",
      "frontmatter": {
        "title": "TypeScript 基础语法",
        "date": "2023-9-13",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "TypeScript"
        ]
      },
      "regularPath": "/BlogItem/TypeScript%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html",
      "relativePath": "BlogItem/TypeScript基础语法.md",
      "key": "v-2707771a",
      "path": "/BlogItem/TypeScript%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html",
      "headers": [
        {
          "level": 2,
          "title": "一、TypeScript基础类型",
          "slug": "一、typescript基础类型"
        },
        {
          "level": 3,
          "title": "1.TypeScript 简介",
          "slug": "_1-typescript-简介"
        },
        {
          "level": 3,
          "title": "2.学习 TS 必须要知道的命令",
          "slug": "_2-学习-ts-必须要知道的命令"
        },
        {
          "level": 3,
          "title": "3.字符串类型",
          "slug": "_3-字符串类型"
        },
        {
          "level": 3,
          "title": "4.数字类型",
          "slug": "_4-数字类型"
        },
        {
          "level": 3,
          "title": "5.布尔类型",
          "slug": "_5-布尔类型"
        },
        {
          "level": 3,
          "title": "6.空值类型",
          "slug": "_6-空值类型"
        },
        {
          "level": 3,
          "title": "7.Null和undefined类型",
          "slug": "_7-null和undefined类型"
        },
        {
          "level": 2,
          "title": "二、任意类型",
          "slug": "二、任意类型"
        },
        {
          "level": 3,
          "title": "1.any 类型",
          "slug": "_1-any-类型"
        },
        {
          "level": 3,
          "title": "2.unknown 顶级类型",
          "slug": "_2-unknown-顶级类型"
        },
        {
          "level": 2,
          "title": "三、接口和对象类型",
          "slug": "三、接口和对象类型"
        },
        {
          "level": 3,
          "title": "1.对象的类型",
          "slug": "_1-对象的类型"
        },
        {
          "level": 3,
          "title": "2.可选属性   使用 ? 操作符",
          "slug": "_2-可选属性-使用-操作符"
        },
        {
          "level": 3,
          "title": "3.任意属性 [propName: string]",
          "slug": "_3-任意属性-propname-string"
        },
        {
          "level": 3,
          "title": "4.只读属性 readonly",
          "slug": "_4-只读属性-readonly"
        },
        {
          "level": 3,
          "title": "5.添加函数",
          "slug": "_5-添加函数"
        },
        {
          "level": 2,
          "title": "四、数组类型",
          "slug": "四、数组类型"
        },
        {
          "level": 3,
          "title": "1.基础写法[ ]",
          "slug": "_1-基础写法"
        },
        {
          "level": 3,
          "title": "2.数组泛型",
          "slug": "_2-数组泛型"
        },
        {
          "level": 3,
          "title": "3.用接口表示数组",
          "slug": "_3-用接口表示数组"
        },
        {
          "level": 3,
          "title": "4.多维数组",
          "slug": "_4-多维数组"
        },
        {
          "level": 3,
          "title": "5.arguments类数组",
          "slug": "_5-arguments类数组"
        },
        {
          "level": 3,
          "title": "6.any 在数组中的应用",
          "slug": "_6-any-在数组中的应用"
        },
        {
          "level": 2,
          "title": "五、函数扩展",
          "slug": "五、函数扩展"
        },
        {
          "level": 3,
          "title": "1.函数的类型",
          "slug": "_1-函数的类型"
        },
        {
          "level": 3,
          "title": "2.函数的可选参数?",
          "slug": "_2-函数的可选参数"
        },
        {
          "level": 3,
          "title": "3.函数参数的默认值",
          "slug": "_3-函数参数的默认值"
        },
        {
          "level": 3,
          "title": "4.接口定义函数",
          "slug": "_4-接口定义函数"
        },
        {
          "level": 3,
          "title": "5.定义剩余参数",
          "slug": "_5-定义剩余参数"
        },
        {
          "level": 3,
          "title": "6.函数重载",
          "slug": "_6-函数重载"
        }
      ],
      "size": "7.60kb"
    },
    {
      "title": "Node.js教程",
      "frontmatter": {
        "title": "Node.js教程",
        "date": "2023-04-12T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Javascript"
        ]
      },
      "regularPath": "/BlogItem/Node.js%E6%95%99%E7%A8%8B.html",
      "relativePath": "BlogItem/Node.js教程.md",
      "key": "v-c07dbf08",
      "path": "/BlogItem/Node.js%E6%95%99%E7%A8%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "一、初识Node.js",
          "slug": "一、初识node-js"
        },
        {
          "level": 2,
          "title": "1.初识Node.js",
          "slug": "_1-初识node-js"
        },
        {
          "level": 2,
          "title": "2.fs文件系统模块",
          "slug": "_2-fs文件系统模块"
        },
        {
          "level": 3,
          "title": "1.fs.readFile() 方法",
          "slug": "_1-fs-readfile-方法"
        },
        {
          "level": 3,
          "title": "2.fs.writeFile() 方法",
          "slug": "_2-fs-writefile-方法"
        },
        {
          "level": 2,
          "title": "3.path路径模块",
          "slug": "_3-path路径模块"
        },
        {
          "level": 3,
          "title": "1.path.join() 方法",
          "slug": "_1-path-join-方法"
        },
        {
          "level": 3,
          "title": "2.path.basename() 方法",
          "slug": "_2-path-basename-方法"
        },
        {
          "level": 3,
          "title": "3.path.extname() 方法",
          "slug": "_3-path-extname-方法"
        },
        {
          "level": 3,
          "title": "4.综合案例——时钟",
          "slug": "_4-综合案例-时钟"
        },
        {
          "level": 2,
          "title": "4.http服务器模块",
          "slug": "_4-http服务器模块"
        },
        {
          "level": 3,
          "title": "1.创建最基本的web服务器",
          "slug": "_1-创建最基本的web服务器"
        },
        {
          "level": 3,
          "title": "2.req 请求对象 res 响应对象",
          "slug": "_2-req-请求对象-res-响应对象"
        },
        {
          "level": 3,
          "title": "3.解决中文乱码",
          "slug": "_3-解决中文乱码"
        },
        {
          "level": 3,
          "title": "4.根据不同的 url 响应不同的 html 内容",
          "slug": "_4-根据不同的-url-响应不同的-html-内容"
        },
        {
          "level": 3,
          "title": "5.综合案例——实现 clock 时钟的 web 服务器",
          "slug": "_5-综合案例-实现-clock-时钟的-web-服务器"
        },
        {
          "level": 2,
          "title": "二、模块化",
          "slug": "二、模块化"
        },
        {
          "level": 2,
          "title": "1.模块化的基本概念",
          "slug": "_1-模块化的基本概念"
        },
        {
          "level": 3,
          "title": "1.模块化",
          "slug": "_1-模块化"
        },
        {
          "level": 3,
          "title": "2.模块化规范",
          "slug": "_2-模块化规范"
        },
        {
          "level": 2,
          "title": "2.Node.js 中的模块化",
          "slug": "_2-node-js-中的模块化"
        },
        {
          "level": 3,
          "title": "1.Node.js 中的模块分类",
          "slug": "_1-node-js-中的模块分类"
        },
        {
          "level": 3,
          "title": "2.加载模块",
          "slug": "_2-加载模块"
        },
        {
          "level": 3,
          "title": "3.Node.js 中的模块作用域",
          "slug": "_3-node-js-中的模块作用域"
        },
        {
          "level": 3,
          "title": "4.向外共享模块作用域中的成员",
          "slug": "_4-向外共享模块作用域中的成员"
        },
        {
          "level": 3,
          "title": "5.Node.js 中的模块化规范",
          "slug": "_5-node-js-中的模块化规范"
        },
        {
          "level": 2,
          "title": "3.npm 与 包",
          "slug": "_3-npm-与-包"
        },
        {
          "level": 3,
          "title": "1.包",
          "slug": "_1-包"
        },
        {
          "level": 3,
          "title": "2.npm 初体验",
          "slug": "_2-npm-初体验"
        },
        {
          "level": 3,
          "title": "3.包管理配置文件",
          "slug": "_3-包管理配置文件"
        },
        {
          "level": 3,
          "title": "4.解决下包速度慢的问题",
          "slug": "_4-解决下包速度慢的问题"
        },
        {
          "level": 3,
          "title": "5.包的分类",
          "slug": "_5-包的分类"
        },
        {
          "level": 3,
          "title": "6.规范的包结构",
          "slug": "_6-规范的包结构"
        },
        {
          "level": 2,
          "title": "4.模块加载机制",
          "slug": "_4-模块加载机制"
        },
        {
          "level": 3,
          "title": "1.优先从缓存中加载",
          "slug": "_1-优先从缓存中加载"
        },
        {
          "level": 3,
          "title": "2.内置模块的加载机制",
          "slug": "_2-内置模块的加载机制"
        },
        {
          "level": 3,
          "title": "3.自定义模块的加载机制",
          "slug": "_3-自定义模块的加载机制"
        },
        {
          "level": 3,
          "title": "4.第三方模块的加载机制",
          "slug": "_4-第三方模块的加载机制"
        },
        {
          "level": 3,
          "title": "5.目录作为模块",
          "slug": "_5-目录作为模块"
        },
        {
          "level": 2,
          "title": "三、Express",
          "slug": "三、express"
        },
        {
          "level": 2,
          "title": "1.初识 Express",
          "slug": "_1-初识-express"
        },
        {
          "level": 3,
          "title": "1.Express 简介",
          "slug": "_1-express-简介"
        },
        {
          "level": 3,
          "title": "2.Express 的基本使用",
          "slug": "_2-express-的基本使用"
        },
        {
          "level": 3,
          "title": "3.托管静态资源",
          "slug": "_3-托管静态资源"
        },
        {
          "level": 3,
          "title": "4.nodemon",
          "slug": "_4-nodemon"
        },
        {
          "level": 2,
          "title": "2.Express 路由",
          "slug": "_2-express-路由"
        },
        {
          "level": 3,
          "title": "1.路由的概念",
          "slug": "_1-路由的概念"
        },
        {
          "level": 3,
          "title": "2.路由的使用",
          "slug": "_2-路由的使用"
        },
        {
          "level": 2,
          "title": "3.Express 中间件",
          "slug": "_3-express-中间件"
        },
        {
          "level": 3,
          "title": "1.中间件的概念",
          "slug": "_1-中间件的概念"
        },
        {
          "level": 3,
          "title": "2.Express 中间件的初体验",
          "slug": "_2-express-中间件的初体验"
        },
        {
          "level": 3,
          "title": "3.中间件的分类",
          "slug": "_3-中间件的分类"
        },
        {
          "level": 3,
          "title": "4.综合案例——自定义中间件",
          "slug": "_4-综合案例-自定义中间件"
        },
        {
          "level": 2,
          "title": "4.使用 Express 写接口",
          "slug": "_4-使用-express-写接口"
        },
        {
          "level": 3,
          "title": "1.创建基本的服务器",
          "slug": "_1-创建基本的服务器"
        },
        {
          "level": 3,
          "title": "2.创建 API 路由模块",
          "slug": "_2-创建-api-路由模块"
        },
        {
          "level": 3,
          "title": "3.编写 GET 接口",
          "slug": "_3-编写-get-接口"
        },
        {
          "level": 3,
          "title": "4.编写 POST 接口",
          "slug": "_4-编写-post-接口"
        },
        {
          "level": 3,
          "title": "5.CORS 跨域资源共享",
          "slug": "_5-cors-跨域资源共享"
        },
        {
          "level": 3,
          "title": "6.JSONP 接口",
          "slug": "_6-jsonp-接口"
        },
        {
          "level": 2,
          "title": "四、数据库与身份认证",
          "slug": "四、数据库与身份认证"
        },
        {
          "level": 2,
          "title": "1.数据库的基本概念",
          "slug": "_1-数据库的基本概念"
        },
        {
          "level": 3,
          "title": "1.什么是数据库",
          "slug": "_1-什么是数据库"
        },
        {
          "level": 3,
          "title": "2.常见的数据库及分类",
          "slug": "_2-常见的数据库及分类"
        },
        {
          "level": 3,
          "title": "3.传统型数据库的数据组织结构",
          "slug": "_3-传统型数据库的数据组织结构"
        },
        {
          "level": 2,
          "title": "2.安装并配置 MySql",
          "slug": "_2-安装并配置-mysql"
        },
        {
          "level": 2,
          "title": "3.MySQL 的基本使用",
          "slug": "_3-mysql-的基本使用"
        },
        {
          "level": 3,
          "title": "1. SQL 的 SELECT 语句",
          "slug": "_1-sql-的-select-语句"
        },
        {
          "level": 3,
          "title": "2.SQL 的 INSERT INTO 语句",
          "slug": "_2-sql-的-insert-into-语句"
        },
        {
          "level": 3,
          "title": "3.SQL 的 UPDATE 语句",
          "slug": "_3-sql-的-update-语句"
        },
        {
          "level": 3,
          "title": "4.SQL 的 DELETE 语句",
          "slug": "_4-sql-的-delete-语句"
        },
        {
          "level": 3,
          "title": "5.SQL 的 WHERE 子句",
          "slug": "_5-sql-的-where-子句"
        },
        {
          "level": 3,
          "title": "6.SQL 的 AND 和 OR 运算符",
          "slug": "_6-sql-的-and-和-or-运算符"
        },
        {
          "level": 3,
          "title": "7.SQL 的 ORDER BY 子句",
          "slug": "_7-sql-的-order-by-子句"
        },
        {
          "level": 3,
          "title": "8.SQL 的 COUNT(*)函数",
          "slug": "_8-sql-的-count-函数"
        },
        {
          "level": 2,
          "title": "4.在项目中操作 MySQL",
          "slug": "_4-在项目中操作-mysql"
        },
        {
          "level": 3,
          "title": "1.在项目中操作数据库的步骤",
          "slug": "_1-在项目中操作数据库的步骤"
        },
        {
          "level": 3,
          "title": "2.安装与配置 mysql 模块",
          "slug": "_2-安装与配置-mysql-模块"
        },
        {
          "level": 3,
          "title": "3.使用 mysql 模块操作 MySQL 数据库",
          "slug": "_3-使用-mysql-模块操作-mysql-数据库"
        },
        {
          "level": 2,
          "title": "5.前后端身份认证",
          "slug": "_5-前后端身份认证"
        },
        {
          "level": 3,
          "title": "1.Web 开发模式",
          "slug": "_1-web-开发模式"
        },
        {
          "level": 3,
          "title": "2.身份认证",
          "slug": "_2-身份认证"
        },
        {
          "level": 3,
          "title": "3.Session 认证机制",
          "slug": "_3-session-认证机制"
        },
        {
          "level": 3,
          "title": "4.在 Express 中使用 Session 认证",
          "slug": "_4-在-express-中使用-session-认证"
        },
        {
          "level": 3,
          "title": "5.JWT 认证机制",
          "slug": "_5-jwt-认证机制"
        },
        {
          "level": 3,
          "title": "6.在 Express 中使用 JWT",
          "slug": "_6-在-express-中使用-jwt"
        }
      ],
      "size": "53.99kb"
    },
    {
      "title": "TypeScript 进阶语法",
      "frontmatter": {
        "title": "TypeScript 进阶语法",
        "date": "2023-9-14",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "TypeScript"
        ]
      },
      "regularPath": "/BlogItem/TypeScript%E8%BF%9B%E9%98%B6%E8%AF%AD%E6%B3%95.html",
      "relativePath": "BlogItem/TypeScript进阶语法.md",
      "key": "v-ba2d4322",
      "path": "/BlogItem/TypeScript%E8%BF%9B%E9%98%B6%E8%AF%AD%E6%B3%95.html",
      "headers": [
        {
          "level": 2,
          "title": "六、类型断言 联合类型 交叉类型",
          "slug": "六、类型断言-联合类型-交叉类型"
        },
        {
          "level": 3,
          "title": "1.联合类型",
          "slug": "_1-联合类型"
        },
        {
          "level": 3,
          "title": "2.交叉类型",
          "slug": "_2-交叉类型"
        },
        {
          "level": 3,
          "title": "3.类型断言",
          "slug": "_3-类型断言"
        },
        {
          "level": 3,
          "title": "4.使用any临时断言",
          "slug": "_4-使用any临时断言"
        },
        {
          "level": 3,
          "title": "5.类型断言是不具影响力的",
          "slug": "_5-类型断言是不具影响力的"
        },
        {
          "level": 2,
          "title": "七、内置对象",
          "slug": "七、内置对象"
        },
        {
          "level": 3,
          "title": "1.ECMAScript 的内置对象",
          "slug": "_1-ecmascript-的内置对象"
        },
        {
          "level": 3,
          "title": "2.DOM 和 BOM 的内置对象",
          "slug": "_2-dom-和-bom-的内置对象"
        },
        {
          "level": 3,
          "title": "3.定义Promise",
          "slug": "_3-定义promise"
        },
        {
          "level": 3,
          "title": "4.案例：TS + Canvas 实现代码雨",
          "slug": "_4-案例-ts-canvas-实现代码雨"
        },
        {
          "level": 2,
          "title": "八、Class  类",
          "slug": "八、class-类"
        },
        {
          "level": 3,
          "title": "1.类的概念",
          "slug": "_1-类的概念"
        },
        {
          "level": 3,
          "title": "2.类的修饰符",
          "slug": "_2-类的修饰符"
        },
        {
          "level": 3,
          "title": "3.static 静态属性 和 静态方法",
          "slug": "_3-static-静态属性-和-静态方法"
        },
        {
          "level": 3,
          "title": "4.interface 定义 类",
          "slug": "_4-interface-定义-类"
        },
        {
          "level": 3,
          "title": "5.抽象类",
          "slug": "_5-抽象类"
        },
        {
          "level": 3,
          "title": "6.案例：手写 Vue 虚拟 Dom",
          "slug": "_6-案例-手写-vue-虚拟-dom"
        },
        {
          "level": 2,
          "title": "九、元组类型",
          "slug": "九、元组类型"
        },
        {
          "level": 3,
          "title": "1.元组就是数组的变种",
          "slug": "_1-元组就是数组的变种"
        },
        {
          "level": 3,
          "title": "2.越界元素",
          "slug": "_2-越界元素"
        },
        {
          "level": 3,
          "title": "3.应用场景",
          "slug": "_3-应用场景"
        },
        {
          "level": 2,
          "title": "十、枚举类型",
          "slug": "十、枚举类型"
        },
        {
          "level": 3,
          "title": "1.数字枚举",
          "slug": "_1-数字枚举"
        },
        {
          "level": 3,
          "title": "2.字符串枚举",
          "slug": "_2-字符串枚举"
        },
        {
          "level": 3,
          "title": "3.异构枚举",
          "slug": "_3-异构枚举"
        },
        {
          "level": 3,
          "title": "4.接口枚举",
          "slug": "_4-接口枚举"
        },
        {
          "level": 3,
          "title": "5.const枚举",
          "slug": "_5-const枚举"
        },
        {
          "level": 3,
          "title": "6.反向映射",
          "slug": "_6-反向映射"
        }
      ],
      "size": "13.67kb"
    },
    {
      "title": "vue3 Ⅰ vue 基础入门",
      "frontmatter": {
        "title": "vue3 Ⅰ vue 基础入门",
        "date": "2023-04-16T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Javascript",
          "Vue"
        ]
      },
      "regularPath": "/BlogItem/vue3%20%E2%85%A0%20vue%20%E5%9F%BA%E7%A1%80%E5%85%A5%E9%97%A8.html",
      "relativePath": "BlogItem/vue3 Ⅰ vue 基础入门.md",
      "key": "v-a6a3607c",
      "path": "/BlogItem/vue3%20%E2%85%A0%20vue%20%E5%9F%BA%E7%A1%80%E5%85%A5%E9%97%A8.html",
      "headers": [
        {
          "level": 2,
          "title": "一、Vue简介",
          "slug": "一、vue简介"
        },
        {
          "level": 3,
          "title": "1.Vue数据驱动",
          "slug": "_1-vue数据驱动"
        },
        {
          "level": 3,
          "title": "2.Vue的版本",
          "slug": "_2-vue的版本"
        },
        {
          "level": 2,
          "title": "二、Vue的基本使用",
          "slug": "二、vue的基本使用"
        },
        {
          "level": 3,
          "title": "1.基本使用步骤",
          "slug": "_1-基本使用步骤"
        },
        {
          "level": 3,
          "title": "2.基本代码与 MVVM 的对应关系",
          "slug": "_2-基本代码与-mvvm-的对应关系"
        },
        {
          "level": 3,
          "title": "3.安装 Vue-devtools 调试工具",
          "slug": "_3-安装-vue-devtools-调试工具"
        },
        {
          "level": 2,
          "title": "三、Vue的指令和过滤器",
          "slug": "三、vue的指令和过滤器"
        },
        {
          "level": 3,
          "title": "1.指令的概念",
          "slug": "_1-指令的概念"
        },
        {
          "level": 3,
          "title": "2.过滤器",
          "slug": "_2-过滤器"
        },
        {
          "level": 2,
          "title": "四、第一个案例——品牌列表案例",
          "slug": "四、第一个案例-品牌列表案例"
        },
        {
          "level": 3,
          "title": "1.案例描述",
          "slug": "_1-案例描述"
        },
        {
          "level": 3,
          "title": "2.案例实现",
          "slug": "_2-案例实现"
        },
        {
          "level": 3,
          "title": "3.案例最终代码",
          "slug": "_3-案例最终代码"
        },
        {
          "level": 2,
          "title": "五、Vue基础入门总结",
          "slug": "五、vue基础入门总结"
        }
      ],
      "size": "28.65kb"
    },
    {
      "title": "vue3 Ⅲ vue 组件基础（下）",
      "frontmatter": {
        "title": "vue3 Ⅲ vue 组件基础（下）",
        "date": "2023-04-20T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Javascript",
          "Vue"
        ]
      },
      "regularPath": "/BlogItem/vue3%20%E2%85%A2%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8B%EF%BC%89.html",
      "relativePath": "BlogItem/vue3 Ⅲ vue 组件基础（下）.md",
      "key": "v-964a33f6",
      "path": "/BlogItem/vue3%20%E2%85%A2%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8B%EF%BC%89.html",
      "headers": [
        {
          "level": 2,
          "title": "十三、props验证",
          "slug": "十三、props验证"
        },
        {
          "level": 3,
          "title": "1.什么是 props 验证",
          "slug": "_1-什么是-props-验证"
        },
        {
          "level": 3,
          "title": "2.对象类型的 props 节点",
          "slug": "_2-对象类型的-props-节点"
        },
        {
          "level": 3,
          "title": "3.props 验证",
          "slug": "_3-props-验证"
        },
        {
          "level": 2,
          "title": "十四、计算属性",
          "slug": "十四、计算属性"
        },
        {
          "level": 3,
          "title": "1.什么是计算属性",
          "slug": "_1-什么是计算属性"
        },
        {
          "level": 3,
          "title": "2.如何声明计算属性",
          "slug": "_2-如何声明计算属性"
        },
        {
          "level": 3,
          "title": "3.计算属性的使用注意点",
          "slug": "_3-计算属性的使用注意点"
        },
        {
          "level": 3,
          "title": "4.计算属性和方法的区别",
          "slug": "_4-计算属性和方法的区别"
        },
        {
          "level": 3,
          "title": "5.计算属性案例",
          "slug": "_5-计算属性案例"
        },
        {
          "level": 2,
          "title": "十五、自定义事件",
          "slug": "十五、自定义事件"
        },
        {
          "level": 3,
          "title": "1.什么是自定义事件",
          "slug": "_1-什么是自定义事件"
        },
        {
          "level": 3,
          "title": "2.自定义事件的3个使用步骤",
          "slug": "_2-自定义事件的3个使用步骤"
        },
        {
          "level": 3,
          "title": "3.自定义事件传参",
          "slug": "_3-自定义事件传参"
        },
        {
          "level": 2,
          "title": "十六、组件上的 v-model",
          "slug": "十六、组件上的-v-model"
        },
        {
          "level": 3,
          "title": "1. 为什么需要在组件上使用 v-model",
          "slug": "_1-为什么需要在组件上使用-v-model"
        },
        {
          "level": 3,
          "title": "2. 在组件上使用 v-model 的步骤",
          "slug": "_2-在组件上使用-v-model-的步骤"
        },
        {
          "level": 2,
          "title": "十七、第三个案例——任务列表案例",
          "slug": "十七、第三个案例-任务列表案例"
        },
        {
          "level": 3,
          "title": "1.案例效果",
          "slug": "_1-案例效果"
        },
        {
          "level": 3,
          "title": "2.用到的知识点",
          "slug": "_2-用到的知识点"
        },
        {
          "level": 3,
          "title": "3.整体实现步骤",
          "slug": "_3-整体实现步骤"
        },
        {
          "level": 3,
          "title": "4.具体实现",
          "slug": "_4-具体实现"
        },
        {
          "level": 2,
          "title": "十八、vue组件基础（下）总结",
          "slug": "十八、vue组件基础-下-总结"
        }
      ],
      "size": "22.27kb"
    },
    {
      "title": "vue3 Ⅱ vue 组件基础（上）",
      "frontmatter": {
        "title": "vue3 Ⅱ vue 组件基础（上）",
        "date": "2023-04-18T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Javascript",
          "Vue"
        ]
      },
      "regularPath": "/BlogItem/vue3%20%E2%85%A1%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8A%EF%BC%89.html",
      "relativePath": "BlogItem/vue3 Ⅱ vue 组件基础（上）.md",
      "key": "v-b9fb28f6",
      "path": "/BlogItem/vue3%20%E2%85%A1%20vue%20%E7%BB%84%E4%BB%B6%E5%9F%BA%E7%A1%80%EF%BC%88%E4%B8%8A%EF%BC%89.html",
      "headers": [
        {
          "level": 2,
          "title": "六、单页面应用程序",
          "slug": "六、单页面应用程序"
        },
        {
          "level": 3,
          "title": "1.什么是单页面应用程序",
          "slug": "_1-什么是单页面应用程序"
        },
        {
          "level": 3,
          "title": "2.单页面应用程序的特点",
          "slug": "_2-单页面应用程序的特点"
        },
        {
          "level": 3,
          "title": "3.单页面应用程序的优缺点",
          "slug": "_3-单页面应用程序的优缺点"
        },
        {
          "level": 3,
          "title": "4.如何快速创建Vue的SPA项目",
          "slug": "_4-如何快速创建vue的spa项目"
        },
        {
          "level": 2,
          "title": "七、vite的基本使用",
          "slug": "七、vite的基本使用"
        },
        {
          "level": 3,
          "title": "1.创建 vite 项目",
          "slug": "_1-创建-vite-项目"
        },
        {
          "level": 3,
          "title": "2.梳理项目的结构",
          "slug": "_2-梳理项目的结构"
        },
        {
          "level": 3,
          "title": "3. vite 项目的运行流程",
          "slug": "_3-vite-项目的运行流程"
        },
        {
          "level": 2,
          "title": "八、组件化开发思想",
          "slug": "八、组件化开发思想"
        },
        {
          "level": 3,
          "title": "1.什么是组件化开发思想",
          "slug": "_1-什么是组件化开发思想"
        },
        {
          "level": 3,
          "title": "2.前端组件化开发的好处",
          "slug": "_2-前端组件化开发的好处"
        },
        {
          "level": 3,
          "title": "3.vue中的组件化开发",
          "slug": "_3-vue中的组件化开发"
        },
        {
          "level": 2,
          "title": "九、vue 组件的构成",
          "slug": "九、vue-组件的构成"
        },
        {
          "level": 3,
          "title": "1.vue 组件组成结构",
          "slug": "_1-vue-组件组成结构"
        },
        {
          "level": 3,
          "title": "2.组件的 template 节点",
          "slug": "_2-组件的-template-节点"
        },
        {
          "level": 3,
          "title": "3.组件的 script 节点",
          "slug": "_3-组件的-script-节点"
        },
        {
          "level": 2,
          "title": "十、组件的基本使用",
          "slug": "十、组件的基本使用"
        },
        {
          "level": 3,
          "title": "1.组件的注册",
          "slug": "_1-组件的注册"
        },
        {
          "level": 3,
          "title": "2.组件之间的样式冲突问题",
          "slug": "_2-组件之间的样式冲突问题"
        },
        {
          "level": 3,
          "title": "3.组件的 props",
          "slug": "_3-组件的-props"
        },
        {
          "level": 3,
          "title": "4. Class 和 Style 绑定",
          "slug": "_4-class-和-style-绑定"
        },
        {
          "level": 2,
          "title": "十一、第二个案例——封装组件案例",
          "slug": "十一、第二个案例-封装组件案例"
        },
        {
          "level": 3,
          "title": "1.案例描述",
          "slug": "_1-案例描述"
        },
        {
          "level": 3,
          "title": "2.案例实现代码",
          "slug": "_2-案例实现代码"
        },
        {
          "level": 2,
          "title": "十二、vue 组件基础（上）总结",
          "slug": "十二、vue-组件基础-上-总结"
        }
      ],
      "size": "13.80kb"
    },
    {
      "title": "vue3 V vue 组件高级（下）",
      "frontmatter": {
        "title": "vue3 V vue 组件高级（下）",
        "date": "2023-04-24T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Javascript",
          "Vue"
        ]
      },
      "regularPath": "/BlogItem/vue3%20%E2%85%A4%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8B%EF%BC%89.html",
      "relativePath": "BlogItem/vue3 Ⅴ vue 组件高级（下）.md",
      "key": "v-7748193b",
      "path": "/BlogItem/vue3%20%E2%85%A4%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8B%EF%BC%89.html",
      "headers": [
        {
          "level": 2,
          "title": "二十五、ref 引用",
          "slug": "二十五、ref-引用"
        },
        {
          "level": 3,
          "title": "1.什么是 ref 引用",
          "slug": "_1-什么是-ref-引用"
        },
        {
          "level": 3,
          "title": "2.使用 ref 引用 DOM 元素",
          "slug": "_2-使用-ref-引用-dom-元素"
        },
        {
          "level": 3,
          "title": "3.使用 ref 引用组件实例",
          "slug": "_3-使用-ref-引用组件实例"
        },
        {
          "level": 3,
          "title": "4.控制文本框和按钮的按需切换",
          "slug": "_4-控制文本框和按钮的按需切换"
        },
        {
          "level": 3,
          "title": "5.让文本框自动获得焦点",
          "slug": "_5-让文本框自动获得焦点"
        },
        {
          "level": 2,
          "title": "二十六、动态组件",
          "slug": "二十六、动态组件"
        },
        {
          "level": 3,
          "title": "1.什么是动态组件",
          "slug": "_1-什么是动态组件"
        },
        {
          "level": 3,
          "title": "2.如何实现动态组件渲染",
          "slug": "_2-如何实现动态组件渲染"
        },
        {
          "level": 3,
          "title": "3.使用 keep-alive 保持状态",
          "slug": "_3-使用-keep-alive-保持状态"
        },
        {
          "level": 2,
          "title": "二十七、插槽",
          "slug": "二十七、插槽"
        },
        {
          "level": 3,
          "title": "1.什么是插槽",
          "slug": "_1-什么是插槽"
        },
        {
          "level": 3,
          "title": "2.插槽的基础用法",
          "slug": "_2-插槽的基础用法"
        },
        {
          "level": 3,
          "title": "3.具名插槽",
          "slug": "_3-具名插槽"
        },
        {
          "level": 3,
          "title": "4.作用域插槽",
          "slug": "_4-作用域插槽"
        },
        {
          "level": 2,
          "title": "二十八、自定义指令",
          "slug": "二十八、自定义指令"
        },
        {
          "level": 3,
          "title": "1.什么是自定义指令",
          "slug": "_1-什么是自定义指令"
        },
        {
          "level": 3,
          "title": "2.声明私有自定义指令的语法",
          "slug": "_2-声明私有自定义指令的语法"
        },
        {
          "level": 3,
          "title": "3.使用自定义指令",
          "slug": "_3-使用自定义指令"
        },
        {
          "level": 3,
          "title": "4.声明全局自定义指令",
          "slug": "_4-声明全局自定义指令"
        },
        {
          "level": 3,
          "title": "5.updeated 函数",
          "slug": "_5-updeated-函数"
        },
        {
          "level": 3,
          "title": "6.函数简写",
          "slug": "_6-函数简写"
        },
        {
          "level": 3,
          "title": "7.指令的参数值",
          "slug": "_7-指令的参数值"
        },
        {
          "level": 2,
          "title": "二十九、第五个案例——Table 案例",
          "slug": "二十九、第五个案例-table-案例"
        },
        {
          "level": 3,
          "title": "1.案例描述",
          "slug": "_1-案例描述"
        },
        {
          "level": 3,
          "title": "2.具体实现",
          "slug": "_2-具体实现"
        },
        {
          "level": 3,
          "title": "3.完整代码",
          "slug": "_3-完整代码"
        },
        {
          "level": 2,
          "title": "三十、vue 组件高级（下）总结",
          "slug": "三十、vue-组件高级-下-总结"
        }
      ],
      "size": "24.11kb"
    },
    {
      "title": "vue3 Ⅳ vue 组件高级（上）",
      "frontmatter": {
        "title": "vue3 Ⅳ vue 组件高级（上）",
        "date": "2023-04-22T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Javascript",
          "Vue"
        ]
      },
      "regularPath": "/BlogItem/vue3%20%E2%85%A3%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8A%EF%BC%89.html",
      "relativePath": "BlogItem/vue3 Ⅳ vue 组件高级（上）.md",
      "key": "v-656f9ebb",
      "path": "/BlogItem/vue3%20%E2%85%A3%20vue%20%E7%BB%84%E4%BB%B6%E9%AB%98%E7%BA%A7%EF%BC%88%E4%B8%8A%EF%BC%89.html",
      "headers": [
        {
          "level": 2,
          "title": "十九、watch 侦听器",
          "slug": "十九、watch-侦听器"
        },
        {
          "level": 3,
          "title": "1.什么是 watch 侦听器",
          "slug": "_1-什么是-watch-侦听器"
        },
        {
          "level": 3,
          "title": "2.watch 侦听器的基本语法",
          "slug": "_2-watch-侦听器的基本语法"
        },
        {
          "level": 3,
          "title": "3.使用 watch 检测用户名是否可用",
          "slug": "_3-使用-watch-检测用户名是否可用"
        },
        {
          "level": 3,
          "title": "4.immediate 选项",
          "slug": "_4-immediate-选项"
        },
        {
          "level": 3,
          "title": "5.deep 选项",
          "slug": "_5-deep-选项"
        },
        {
          "level": 3,
          "title": "6.监听对象单个属性的变化",
          "slug": "_6-监听对象单个属性的变化"
        },
        {
          "level": 3,
          "title": "7.计算属性 vs 侦听器",
          "slug": "_7-计算属性-vs-侦听器"
        },
        {
          "level": 2,
          "title": "二十、组件的生命周期",
          "slug": "二十、组件的生命周期"
        },
        {
          "level": 3,
          "title": "1.组件的运行过程",
          "slug": "_1-组件的运行过程"
        },
        {
          "level": 3,
          "title": "2.如何监听组件的不同时刻",
          "slug": "_2-如何监听组件的不同时刻"
        },
        {
          "level": 3,
          "title": "3.如何监听组件的更新",
          "slug": "_3-如何监听组件的更新"
        },
        {
          "level": 3,
          "title": "4.组件中主要的生命周期函数",
          "slug": "_4-组件中主要的生命周期函数"
        },
        {
          "level": 3,
          "title": "5.组件中全部的生命周期函数",
          "slug": "_5-组件中全部的生命周期函数"
        },
        {
          "level": 3,
          "title": "6.完整的生命周期图示",
          "slug": "_6-完整的生命周期图示"
        },
        {
          "level": 2,
          "title": "二十一、组件之间的数据共享",
          "slug": "二十一、组件之间的数据共享"
        },
        {
          "level": 3,
          "title": "1.组件之间的关系",
          "slug": "_1-组件之间的关系"
        },
        {
          "level": 3,
          "title": "2.父子组件之间的数据共享",
          "slug": "_2-父子组件之间的数据共享"
        },
        {
          "level": 3,
          "title": "3.兄弟组件之间的数据共享",
          "slug": "_3-兄弟组件之间的数据共享"
        },
        {
          "level": 3,
          "title": "4.后代关系组件之间的数据共享",
          "slug": "_4-后代关系组件之间的数据共享"
        },
        {
          "level": 3,
          "title": "5.vuex",
          "slug": "_5-vuex"
        },
        {
          "level": 3,
          "title": "6.总结",
          "slug": "_6-总结"
        },
        {
          "level": 2,
          "title": "二十二、vue 3.x 中全局配置 axios",
          "slug": "二十二、vue-3-x-中全局配置-axios"
        },
        {
          "level": 3,
          "title": "1.为什么要全局配置 axios",
          "slug": "_1-为什么要全局配置-axios"
        },
        {
          "level": 3,
          "title": "2.如何全局配置 axios",
          "slug": "_2-如何全局配置-axios"
        },
        {
          "level": 3,
          "title": "3.使用 axios",
          "slug": "_3-使用-axios"
        },
        {
          "level": 2,
          "title": "二十三、第四个案例——购物车案例",
          "slug": "二十三、第四个案例-购物车案例"
        },
        {
          "level": 3,
          "title": "1.案例效果",
          "slug": "_1-案例效果"
        },
        {
          "level": 3,
          "title": "2.实现步骤",
          "slug": "_2-实现步骤"
        },
        {
          "level": 3,
          "title": "3.具体实现",
          "slug": "_3-具体实现"
        },
        {
          "level": 2,
          "title": "二十四、vue组件高级（上）总结",
          "slug": "二十四、vue组件高级-上-总结"
        }
      ],
      "size": "34.82kb"
    },
    {
      "title": "vue3 Ⅵ vue 路由",
      "frontmatter": {
        "title": "vue3 Ⅵ vue 路由",
        "date": "2023-04-26T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Javascript",
          "Vue"
        ]
      },
      "regularPath": "/BlogItem/vue3%20%E2%85%A5%20vue%20%E8%B7%AF%E7%94%B1.html",
      "relativePath": "BlogItem/vue3 Ⅵ vue 路由.md",
      "key": "v-9d78ab64",
      "path": "/BlogItem/vue3%20%E2%85%A5%20vue%20%E8%B7%AF%E7%94%B1.html",
      "headers": [
        {
          "level": 2,
          "title": "三十一、前端路由的概念与原理",
          "slug": "三十一、前端路由的概念与原理"
        },
        {
          "level": 3,
          "title": "1.什么是路由",
          "slug": "_1-什么是路由"
        },
        {
          "level": 3,
          "title": "2.回顾：后端路由",
          "slug": "_2-回顾-后端路由"
        },
        {
          "level": 3,
          "title": "3.SPA 与前端路由",
          "slug": "_3-spa-与前端路由"
        },
        {
          "level": 3,
          "title": "4.什么是前端路由",
          "slug": "_4-什么是前端路由"
        },
        {
          "level": 3,
          "title": "5.前端路由的工作方式",
          "slug": "_5-前端路由的工作方式"
        },
        {
          "level": 3,
          "title": "6.实现简易的前端路由",
          "slug": "_6-实现简易的前端路由"
        },
        {
          "level": 2,
          "title": "三十二、vue-router 的基本用法",
          "slug": "三十二、vue-router-的基本用法"
        },
        {
          "level": 3,
          "title": "1.什么是 vue-router",
          "slug": "_1-什么是-vue-router"
        },
        {
          "level": 3,
          "title": "2.vue-router 的版本",
          "slug": "_2-vue-router-的版本"
        },
        {
          "level": 3,
          "title": "3.vue-router 4.x 的基本使用步骤",
          "slug": "_3-vue-router-4-x-的基本使用步骤"
        },
        {
          "level": 2,
          "title": "三十三、vue-router 的高级用法",
          "slug": "三十三、vue-router-的高级用法"
        },
        {
          "level": 3,
          "title": "1.路由重定向",
          "slug": "_1-路由重定向"
        },
        {
          "level": 3,
          "title": "2.路由高亮",
          "slug": "_2-路由高亮"
        },
        {
          "level": 3,
          "title": "3.嵌套路由",
          "slug": "_3-嵌套路由"
        },
        {
          "level": 3,
          "title": "4.动态路由匹配",
          "slug": "_4-动态路由匹配"
        },
        {
          "level": 3,
          "title": "5.编程式导航",
          "slug": "_5-编程式导航"
        },
        {
          "level": 3,
          "title": "6.命名路由",
          "slug": "_6-命名路由"
        },
        {
          "level": 3,
          "title": "7.导航守卫",
          "slug": "_7-导航守卫"
        },
        {
          "level": 2,
          "title": "三十四、第六个案例——后台管理案例",
          "slug": "三十四、第六个案例-后台管理案例"
        },
        {
          "level": 3,
          "title": "1.案例效果",
          "slug": "_1-案例效果"
        },
        {
          "level": 3,
          "title": "2.案例用到的知识点",
          "slug": "_2-案例用到的知识点"
        },
        {
          "level": 3,
          "title": "3.具体实现",
          "slug": "_3-具体实现"
        },
        {
          "level": 2,
          "title": "三十五、路由总结",
          "slug": "三十五、路由总结"
        }
      ],
      "size": "21.23kb"
    },
    {
      "title": "vue3 Ⅷ vue 常见优化手段",
      "frontmatter": {
        "title": "vue3 Ⅷ vue 常见优化手段",
        "date": "2023-04-30T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Javascript",
          "Vue"
        ]
      },
      "regularPath": "/BlogItem/vue3%20%E2%85%A7%20vue%20%E5%B8%B8%E8%A7%81%E4%BC%98%E5%8C%96%E6%89%8B%E6%AE%B5.html",
      "relativePath": "BlogItem/vue3 Ⅷ vue 常见优化手段.md",
      "key": "v-cc371236",
      "path": "/BlogItem/vue3%20%E2%85%A7%20vue%20%E5%B8%B8%E8%A7%81%E4%BC%98%E5%8C%96%E6%89%8B%E6%AE%B5.html",
      "headers": [
        {
          "level": 3,
          "title": "0.永远不要过早优化",
          "slug": "_0-永远不要过早优化"
        },
        {
          "level": 3,
          "title": "1.使用 key",
          "slug": "_1-使用-key"
        },
        {
          "level": 3,
          "title": "2.使用冻结的对象",
          "slug": "_2-使用冻结的对象"
        },
        {
          "level": 3,
          "title": "3.使用函数式组件",
          "slug": "_3-使用函数式组件"
        },
        {
          "level": 3,
          "title": "4.使用计算属性",
          "slug": "_4-使用计算属性"
        },
        {
          "level": 3,
          "title": "5.非实时绑定的表单项",
          "slug": "_5-非实时绑定的表单项"
        },
        {
          "level": 3,
          "title": "6.保持对象引用稳定",
          "slug": "_6-保持对象引用稳定"
        },
        {
          "level": 3,
          "title": "7.使用 v-show 替代 v-if",
          "slug": "_7-使用-v-show-替代-v-if"
        },
        {
          "level": 3,
          "title": "8.使用延迟装载（defer）",
          "slug": "_8-使用延迟装载-defer"
        }
      ],
      "size": "2.97kb"
    },
    {
      "title": "vue3 Ⅶ vue 补充内容",
      "frontmatter": {
        "title": "vue3 Ⅶ vue 补充内容",
        "date": "2023-04-28T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Javascript",
          "Vue"
        ]
      },
      "regularPath": "/BlogItem/vue3%20%E2%85%A6%20vue%20%E8%A1%A5%E5%85%85%E5%86%85%E5%AE%B9.html",
      "relativePath": "BlogItem/vue3 Ⅶ vue 补充内容.md",
      "key": "v-4f28a414",
      "path": "/BlogItem/vue3%20%E2%85%A6%20vue%20%E8%A1%A5%E5%85%85%E5%86%85%E5%AE%B9.html",
      "headers": [
        {
          "level": 2,
          "title": "三十六、vue-cli",
          "slug": "三十六、vue-cli"
        },
        {
          "level": 3,
          "title": "1.什么是 vue-cli",
          "slug": "_1-什么是-vue-cli"
        },
        {
          "level": 3,
          "title": "2.安装 vue-cli",
          "slug": "_2-安装-vue-cli"
        },
        {
          "level": 3,
          "title": "3.创建项目",
          "slug": "_3-创建项目"
        },
        {
          "level": 3,
          "title": "4.基于 vue ui 创建 vue 项目",
          "slug": "_4-基于-vue-ui-创建-vue-项目"
        },
        {
          "level": 3,
          "title": "5.基于命令行创建 vue 项目",
          "slug": "_5-基于命令行创建-vue-项目"
        },
        {
          "level": 3,
          "title": "6.分析 main.js 中的主要代码",
          "slug": "_6-分析-main-js-中的主要代码"
        },
        {
          "level": 3,
          "title": "7.在 vue2 的项目中使用路由",
          "slug": "_7-在-vue2-的项目中使用路由"
        },
        {
          "level": 2,
          "title": "三十七、组件库",
          "slug": "三十七、组件库"
        },
        {
          "level": 3,
          "title": "1.什么是组件库",
          "slug": "_1-什么是组件库"
        },
        {
          "level": 3,
          "title": "2.vue 组件库和 bootstrap 的区别",
          "slug": "_2-vue-组件库和-bootstrap-的区别"
        },
        {
          "level": 3,
          "title": "3.最常用的组件库",
          "slug": "_3-最常用的组件库"
        },
        {
          "level": 3,
          "title": "4.Element UI",
          "slug": "_4-element-ui"
        },
        {
          "level": 2,
          "title": "三十八、axios 拦截器",
          "slug": "三十八、axios-拦截器"
        },
        {
          "level": 3,
          "title": "1.回顾：在 vue3 的项目中全局配置 axios",
          "slug": "_1-回顾-在-vue3-的项目中全局配置-axios"
        },
        {
          "level": 3,
          "title": "2.在 vue2 的项目中全局配置 axios",
          "slug": "_2-在-vue2-的项目中全局配置-axios"
        },
        {
          "level": 3,
          "title": "3.什么是拦截器",
          "slug": "_3-什么是拦截器"
        },
        {
          "level": 3,
          "title": "4.配置请求拦截器",
          "slug": "_4-配置请求拦截器"
        },
        {
          "level": 3,
          "title": "5.配置响应拦截器",
          "slug": "_5-配置响应拦截器"
        },
        {
          "level": 2,
          "title": "三十九、proxy 跨域代理",
          "slug": "三十九、proxy-跨域代理"
        },
        {
          "level": 3,
          "title": "1.回顾：接口的跨域问题",
          "slug": "_1-回顾-接口的跨域问题"
        },
        {
          "level": 3,
          "title": "2.通过代理解决接口的跨域问题",
          "slug": "_2-通过代理解决接口的跨域问题"
        },
        {
          "level": 3,
          "title": "3.在项目中配置 proxy 代理",
          "slug": "_3-在项目中配置-proxy-代理"
        },
        {
          "level": 2,
          "title": "四十、用户列表案例",
          "slug": "四十、用户列表案例"
        },
        {
          "level": 3,
          "title": "1.用到的知识点",
          "slug": "_1-用到的知识点"
        },
        {
          "level": 3,
          "title": "2.整体实现步骤",
          "slug": "_2-整体实现步骤"
        },
        {
          "level": 3,
          "title": "3.具体实现",
          "slug": "_3-具体实现"
        },
        {
          "level": 2,
          "title": "四十一、vue 补充内容总结",
          "slug": "四十一、vue-补充内容总结"
        }
      ],
      "size": "15.62kb"
    },
    {
      "title": "vue3与组合式API",
      "frontmatter": {
        "title": "vue3与组合式API",
        "date": "2023-5-15",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Vue"
        ]
      },
      "regularPath": "/BlogItem/vue3%E4%B8%8E%E7%BB%84%E5%90%88%E5%BC%8FAPI.html",
      "relativePath": "BlogItem/vue3与组合式API.md",
      "key": "v-25305652",
      "path": "/BlogItem/vue3%E4%B8%8E%E7%BB%84%E5%90%88%E5%BC%8FAPI.html",
      "headers": [
        {
          "level": 2,
          "title": "认识Vue3",
          "slug": "认识vue3"
        },
        {
          "level": 3,
          "title": "1. Vue3组合式API体验",
          "slug": "_1-vue3组合式api体验"
        },
        {
          "level": 3,
          "title": "2. Vue3更多的优势",
          "slug": "_2-vue3更多的优势"
        },
        {
          "level": 2,
          "title": "使用create-vue搭建Vue3项目",
          "slug": "使用create-vue搭建vue3项目"
        },
        {
          "level": 3,
          "title": "1. 认识create-vue",
          "slug": "_1-认识create-vue"
        },
        {
          "level": 3,
          "title": "2. 使用create-vue创建项目",
          "slug": "_2-使用create-vue创建项目"
        },
        {
          "level": 2,
          "title": "熟悉项目和关键文件",
          "slug": "熟悉项目和关键文件"
        },
        {
          "level": 2,
          "title": "组合式API - setup选项",
          "slug": "组合式api-setup选项"
        },
        {
          "level": 3,
          "title": "1. setup选项的写法和执行时机",
          "slug": "_1-setup选项的写法和执行时机"
        },
        {
          "level": 3,
          "title": "2. setup中写代码的特点",
          "slug": "_2-setup中写代码的特点"
        },
        {
          "level": 3,
          "title": "3. script setup 语法糖",
          "slug": "_3-script-setup-语法糖"
        },
        {
          "level": 2,
          "title": "组合式API - reactive和ref函数",
          "slug": "组合式api-reactive和ref函数"
        },
        {
          "level": 3,
          "title": "1. reactive",
          "slug": "_1-reactive"
        },
        {
          "level": 3,
          "title": "2. ref",
          "slug": "_2-ref"
        },
        {
          "level": 3,
          "title": "3. reactive 对比 ref",
          "slug": "_3-reactive-对比-ref"
        },
        {
          "level": 2,
          "title": "组合式API - computed",
          "slug": "组合式api-computed"
        },
        {
          "level": 2,
          "title": "组合式API - watch",
          "slug": "组合式api-watch"
        },
        {
          "level": 3,
          "title": "1. 侦听单个数据",
          "slug": "_1-侦听单个数据"
        },
        {
          "level": 3,
          "title": "2. 侦听多个数据",
          "slug": "_2-侦听多个数据"
        },
        {
          "level": 3,
          "title": "3. immediate",
          "slug": "_3-immediate"
        },
        {
          "level": 3,
          "title": "4. deep",
          "slug": "_4-deep"
        },
        {
          "level": 2,
          "title": "组合式API - 生命周期函数",
          "slug": "组合式api-生命周期函数"
        },
        {
          "level": 3,
          "title": "1. 选项式对比组合式",
          "slug": "_1-选项式对比组合式"
        },
        {
          "level": 3,
          "title": "2. 生命周期函数基本使用",
          "slug": "_2-生命周期函数基本使用"
        },
        {
          "level": 3,
          "title": "3. 执行多次",
          "slug": "_3-执行多次"
        },
        {
          "level": 2,
          "title": "组合式API - 父子通信",
          "slug": "组合式api-父子通信"
        },
        {
          "level": 3,
          "title": "1. 父传子",
          "slug": "_1-父传子"
        },
        {
          "level": 3,
          "title": "2. 子传父",
          "slug": "_2-子传父"
        },
        {
          "level": 2,
          "title": "组合式API - 模版引用",
          "slug": "组合式api-模版引用"
        },
        {
          "level": 3,
          "title": "1. 基本使用",
          "slug": "_1-基本使用"
        },
        {
          "level": 3,
          "title": "2. defineExpose",
          "slug": "_2-defineexpose"
        },
        {
          "level": 2,
          "title": "组合式API - provide和inject",
          "slug": "组合式api-provide和inject"
        },
        {
          "level": 3,
          "title": "1. 作用和场景",
          "slug": "_1-作用和场景"
        },
        {
          "level": 3,
          "title": "2. 跨层传递普通数据",
          "slug": "_2-跨层传递普通数据"
        },
        {
          "level": 3,
          "title": "3. 跨层传递响应式数据",
          "slug": "_3-跨层传递响应式数据"
        },
        {
          "level": 3,
          "title": "4. 跨层传递方法",
          "slug": "_4-跨层传递方法"
        }
      ],
      "size": "8.12kb"
    },
    {
      "title": "微信支付",
      "frontmatter": {
        "title": "微信支付",
        "date": "2023-09-07T00:00:00.000Z",
        "author": "liuwy",
        "categories": [
          "专题"
        ],
        "tags": [
          "payment"
        ]
      },
      "regularPath": "/BlogItem/%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98.html",
      "relativePath": "BlogItem/微信支付.md",
      "key": "v-28fd3a72",
      "path": "/BlogItem/%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98.html",
      "headers": [
        {
          "level": 2,
          "title": "1、微信支付产品介绍",
          "slug": "_1、微信支付产品介绍"
        },
        {
          "level": 2,
          "title": "2、接入指引",
          "slug": "_2、接入指引"
        },
        {
          "level": 2,
          "title": "3、支付安全（证书/秘钥/签名）",
          "slug": "_3、支付安全-证书-秘钥-签名"
        }
      ],
      "size": "2.83kb"
    },
    {
      "title": "命运之约——我与她的相遇",
      "frontmatter": {
        "title": "命运之约——我与她的相遇",
        "date": "2023-7-15",
        "author": "liuwy",
        "categories": [
          "情感"
        ],
        "tags": [
          "一切都刚刚好"
        ]
      },
      "regularPath": "/BlogItem/%E6%88%91%E4%BB%AC%E7%9A%84%E6%95%85%E4%BA%8B.html",
      "relativePath": "BlogItem/我们的故事.md",
      "key": "v-cbb13aa4",
      "path": "/BlogItem/%E6%88%91%E4%BB%AC%E7%9A%84%E6%95%85%E4%BA%8B.html",
      "headers": [
        {
          "level": 2,
          "title": "01.开端——挣扎",
          "slug": "_01-开端-挣扎"
        },
        {
          "level": 2,
          "title": "02.初识——缘起",
          "slug": "_02-初识-缘起"
        },
        {
          "level": 2,
          "title": "03.熟悉——慢慢进步",
          "slug": "_03-熟悉-慢慢进步"
        }
      ],
      "size": "1.79kb"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.png",
        "heroImageStyle": {
          "width": "200px",
          "height": "200px",
          "display": "block",
          "margin": "6rem auto 1.5rem",
          "borderRadius": "50%",
          "boxShadow": "0 5px 18px rgba(0,0,0,0.2)"
        },
        "bgImageStyle": {
          "height": "450px"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-6ac3a860",
      "path": "/",
      "size": "0.26kb"
    },
    {
      "title": "路径别名 ElementPlus Sass配置",
      "frontmatter": {
        "title": "路径别名 ElementPlus Sass配置",
        "date": "2023-5-30",
        "author": "liuwy",
        "categories": [
          "技术"
        ],
        "tags": [
          "Vue"
        ]
      },
      "regularPath": "/BlogItem/%E8%B7%AF%E5%BE%84%E5%88%AB%E5%90%8D%20ElementPlus%20Sass%E9%85%8D%E7%BD%AE.html",
      "relativePath": "BlogItem/路径别名 ElementPlus Sass配置.md",
      "key": "v-7c16f5de",
      "path": "/BlogItem/%E8%B7%AF%E5%BE%84%E5%88%AB%E5%90%8D%20ElementPlus%20Sass%E9%85%8D%E7%BD%AE.html",
      "headers": [
        {
          "level": 2,
          "title": "创建项目并整理目录",
          "slug": "创建项目并整理目录"
        },
        {
          "level": 3,
          "title": "jsconfig.json配置别名路径",
          "slug": "jsconfig-json配置别名路径"
        },
        {
          "level": 2,
          "title": "elementPlus引入",
          "slug": "elementplus引入"
        },
        {
          "level": 3,
          "title": "1. 安装elementPlus和自动导入插件",
          "slug": "_1-安装elementplus和自动导入插件"
        },
        {
          "level": 3,
          "title": "2. 配置自动按需导入",
          "slug": "_2-配置自动按需导入"
        },
        {
          "level": 3,
          "title": "3. 测试组件",
          "slug": "_3-测试组件"
        },
        {
          "level": 2,
          "title": "定制elementPlus主题",
          "slug": "定制elementplus主题"
        },
        {
          "level": 3,
          "title": "1. 安装sass",
          "slug": "_1-安装sass"
        },
        {
          "level": 3,
          "title": "2. 准备定制化的样式文件",
          "slug": "_2-准备定制化的样式文件"
        },
        {
          "level": 3,
          "title": "3. 自动导入配置",
          "slug": "_3-自动导入配置"
        },
        {
          "level": 2,
          "title": "axios安装并简单封装",
          "slug": "axios安装并简单封装"
        },
        {
          "level": 3,
          "title": "1. 安装axios",
          "slug": "_1-安装axios"
        },
        {
          "level": 3,
          "title": "2. 基础配置",
          "slug": "_2-基础配置"
        },
        {
          "level": 3,
          "title": "3. 封装请求函数并测试",
          "slug": "_3-封装请求函数并测试"
        },
        {
          "level": 2,
          "title": "路由整体设计",
          "slug": "路由整体设计"
        },
        {
          "level": 2,
          "title": "scss变量自动导入",
          "slug": "scss变量自动导入"
        }
      ],
      "size": "4.91kb"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Java Tags"
      },
      "regularPath": "/tag/Java/",
      "key": "v-18082c7a",
      "path": "/tag/Java/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Arrays Tags"
      },
      "regularPath": "/tag/Arrays/",
      "key": "v-255b982b",
      "path": "/tag/Arrays/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "IDEA Tags"
      },
      "regularPath": "/tag/IDEA/",
      "key": "v-184030a4",
      "path": "/tag/IDEA/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "git Tags"
      },
      "regularPath": "/tag/git/",
      "key": "v-32383f72",
      "path": "/tag/git/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Javascript Tags"
      },
      "regularPath": "/tag/Javascript/",
      "key": "v-5f97b358",
      "path": "/tag/Javascript/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Lambda Tags"
      },
      "regularPath": "/tag/Lambda/",
      "key": "v-4df76f3e",
      "path": "/tag/Lambda/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Pinia Tags"
      },
      "regularPath": "/tag/Pinia/",
      "key": "v-d3a8c0a8",
      "path": "/tag/Pinia/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "SpringBoot Tags"
      },
      "regularPath": "/tag/SpringBoot/",
      "key": "v-54cc5f34",
      "path": "/tag/SpringBoot/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "AOP Tags"
      },
      "regularPath": "/tag/AOP/",
      "key": "v-325b9792",
      "path": "/tag/AOP/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "TypeScript Tags"
      },
      "regularPath": "/tag/TypeScript/",
      "key": "v-bee809c0",
      "path": "/tag/TypeScript/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Vue Tags"
      },
      "regularPath": "/tag/Vue/",
      "key": "v-32475d9a",
      "path": "/tag/Vue/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "payment Tags"
      },
      "regularPath": "/tag/payment/",
      "key": "v-21b69f93",
      "path": "/tag/payment/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "一切都刚刚好 Tags"
      },
      "regularPath": "/tag/%E4%B8%80%E5%88%87%E9%83%BD%E5%88%9A%E5%88%9A%E5%A5%BD/",
      "key": "v-d740cc78",
      "path": "/tag/一切都刚刚好/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "技术 Categories"
      },
      "regularPath": "/categories/%E6%8A%80%E6%9C%AF/",
      "key": "v-5cfc18c5",
      "path": "/categories/技术/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "技巧 Categories"
      },
      "regularPath": "/categories/%E6%8A%80%E5%B7%A7/",
      "key": "v-03cd6da0",
      "path": "/categories/技巧/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "专题 Categories"
      },
      "regularPath": "/categories/%E4%B8%93%E9%A2%98/",
      "key": "v-5828c6a2",
      "path": "/categories/专题/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "情感 Categories"
      },
      "regularPath": "/categories/%E6%83%85%E6%84%9F/",
      "key": "v-2e6b8ebc",
      "path": "/categories/情感/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 2 - Javascript | Tags"
      },
      "regularPath": "/tag/Javascript/page/2/",
      "key": "v-306a6f65",
      "path": "/tag/Javascript/page/2/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 2 - 技术 | Categories"
      },
      "regularPath": "/categories/%E6%8A%80%E6%9C%AF/page/2/",
      "key": "v-2c1a8558",
      "path": "/categories/技术/page/2/"
    }
  ],
  "themeConfig": {
    "author": "Liuwy",
    "authorAvatar": "/logo.png",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      },
      "socialLinks": [
        {
          "link": "https://juejin.cn/user/1410020421418286",
          "icon": "reco-juejin"
        },
        {
          "link": "https://github.com/indulgeback",
          "icon": "reco-github"
        },
        {
          "link": "https://blog.csdn.net/weixin_63001592",
          "icon": "reco-csdn"
        }
      ]
    },
    "type": "blog",
    "subSidebar": "auto",
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "TimeLine",
        "link": "/timeLine/",
        "icon": "reco-date"
      },
      {
        "text": "关注我",
        "items": [
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/1410020421418286",
            "icon": "reco-juejin"
          },
          {
            "text": "GitHub",
            "link": "https://github.com/indulgeback",
            "icon": "reco-github"
          },
          {
            "text": "CSDN",
            "link": "https://blog.csdn.net/weixin_63001592",
            "icon": "reco-csdn"
          }
        ],
        "icon": "reco-three"
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}