/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Java": {
      "key": "Java",
      "scope": "tags",
      "path": "/tag/Java/",
      "pageKeys": [
        "v-3e68fda2",
        "v-1de00e7b",
        "v-a2730a74"
      ]
    },
    "Arrays": {
      "key": "Arrays",
      "scope": "tags",
      "path": "/tag/Arrays/",
      "pageKeys": [
        "v-3e68fda2"
      ]
    },
    "Javascript": {
      "key": "Javascript",
      "scope": "tags",
      "path": "/tag/Javascript/",
      "pageKeys": [
        "v-03ea0756",
        "v-28acc7f4",
        "v-1c946e75",
        "v-c07dbf08",
        "v-a6a3607c",
        "v-b9fb28f6",
        "v-964a33f6",
        "v-656f9ebb",
        "v-7748193b",
        "v-9d78ab64",
        "v-4f28a414",
        "v-cc371236"
      ]
    },
    "git": {
      "key": "git",
      "scope": "tags",
      "path": "/tag/git/",
      "pageKeys": [
        "v-af2edb96"
      ]
    },
    "Lambda": {
      "key": "Lambda",
      "scope": "tags",
      "path": "/tag/Lambda/",
      "pageKeys": [
        "v-1de00e7b"
      ]
    },
    "Pinia": {
      "key": "Pinia",
      "scope": "tags",
      "path": "/tag/Pinia/",
      "pageKeys": [
        "v-76aa7db6"
      ]
    },
    "SpringBoot": {
      "key": "SpringBoot",
      "scope": "tags",
      "path": "/tag/SpringBoot/",
      "pageKeys": [
        "v-a2730a74"
      ]
    },
    "AOP": {
      "key": "AOP",
      "scope": "tags",
      "path": "/tag/AOP/",
      "pageKeys": [
        "v-a2730a74"
      ]
    },
    "TypeScript": {
      "key": "TypeScript",
      "scope": "tags",
      "path": "/tag/TypeScript/",
      "pageKeys": [
        "v-ba2d4322",
        "v-2707771a"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "tags",
      "path": "/tag/Vue/",
      "pageKeys": [
        "v-a6a3607c",
        "v-b9fb28f6",
        "v-964a33f6",
        "v-656f9ebb",
        "v-7748193b",
        "v-9d78ab64",
        "v-4f28a414",
        "v-cc371236",
        "v-25305652",
        "v-7c16f5de"
      ]
    },
    "payment": {
      "key": "payment",
      "scope": "tags",
      "path": "/tag/payment/",
      "pageKeys": [
        "v-28fd3a72"
      ]
    },
    "一切都刚刚好": {
      "key": "一切都刚刚好",
      "scope": "tags",
      "path": "/tag/一切都刚刚好/",
      "pageKeys": [
        "v-cbb13aa4"
      ]
    }
  },
  "categories": {
    "技术": {
      "key": "技术",
      "scope": "categories",
      "path": "/categories/技术/",
      "pageKeys": [
        "v-3e68fda2",
        "v-03ea0756",
        "v-af2edb96",
        "v-28acc7f4",
        "v-76aa7db6",
        "v-c07dbf08",
        "v-a2730a74",
        "v-ba2d4322",
        "v-2707771a",
        "v-a6a3607c",
        "v-b9fb28f6",
        "v-964a33f6",
        "v-656f9ebb",
        "v-7748193b",
        "v-9d78ab64",
        "v-4f28a414",
        "v-cc371236",
        "v-25305652",
        "v-7c16f5de"
      ]
    },
    "专题": {
      "key": "专题",
      "scope": "categories",
      "path": "/categories/专题/",
      "pageKeys": [
        "v-1de00e7b",
        "v-1c946e75",
        "v-28fd3a72"
      ]
    },
    "情感": {
      "key": "情感",
      "scope": "categories",
      "path": "/categories/情感/",
      "pageKeys": [
        "v-cbb13aa4"
      ]
    }
  },
  "timeline": {}
}